### ISSUE TITLE
Wish list: TAR support.

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#1]
Would like phpMussel to have the ability to read and parse TAR files. Not quite sure how to go about this at the moment; Help and/or suggestions invited.

**Comment by DanielRuf** [comment]
See https://github.com/Maikuolan/phpMussel/issues/2#issuecomment-105006797

**Comment by Maikuolan** [comment]
Found this: http://www.gnu.org/software/tar/manual/html_node/Standard.html

Putting together something at the moment based on that information that I think I should have finished within the day, hopefully; If it works, I'll send in a commit for it.

**Comment by DanielRuf** [comment]
> #define TMAGIC   "ustar"        /\* ustar and a null */

Great, so we have now all the information about the TAR format specification for the detection of this archive format and much more.

Okay. Please update this issue and link me, when you have commited some implementation and I can test it.

**Comment by Maikuolan** [comment]
@DanielRuf Committed. :-)

I created some arbitrary TAR files using the 7-zip program (I also noticed that the TAR files created by 7-zip don't seem to contain the `ustar\x00` magic number; actually, they don't seem to contain any magic number at all; they do contain the `\x00{1024}` end-block footer, though), and phpMussel (as of this latest commit) seems to be able to correctly read and parse those TAR files without problems, but I haven't yet tested the implemented code against TAR files from anywhere else (because there are a number of slightly different versions of the TAR format - POSIX, [Old]GNU, [New]GNU, etc - it would be good to test it against a wide range of TAR files to know how well it works overall, and for whether it actually works for files other than those created by 7-zip).

There are some lines of code that I've written but commented out within the TAR code section of `phpmussel.inc`, based on the information that we have; These commented out lines, aren't currently used for anything by phpMussel, but could be useful for expanding on TAR support (what the specification mentions about bit-flags, in particular, could be useful, but I haven't yet written anything that makes use of it).

Anyhow, it should now be ready for testing. Let me know how it goes on your end, and if there aren't any problems, I'll close this issue. :-)

**Comment by DanielRuf** [comment]
Right, there are different formats, I have not tested all of them so far.

At least z7ip does not use USTAR, the file just contains the filename(s), content(s) and so on, no actual header as it looks like.

Reference: http://sourceforge.net/p/sevenzip/discussion/45797/thread/1815e053

I will let you know, when I have done more tests and if there are any problems.

**Comment by Maikuolan** [comment]
Just now I found something small that I'd messed up; A new commit has been made. Sorry about that! ^.^

And cheers. :-)

**Comment by DanielRuf** [comment]
No problem, thanks for the heads up, will translate this right now.

**Comment by DanielRuf** [comment]
I have tested TAR files (created them using 7z, Peazip and WinRar) and so far there are no problems. The files and the contents were detected by phpMussel, but will do some bigger tests this week.

**Comment by Maikuolan** [comment]
Awesome; Looking forward to hearing how it goes. :-)

**Comment by DanielRuf** [comment]
The normal tests ran without any problems, so we have now a basic working tar implementation.

tar in tar (recursive scan), scan file contents in rar (exe, binary / meta, ...) and some more may need to be added in the future for sure.

**Comment by Maikuolan** [comment]
Good to hear. :-)

As TAR support is now implemented and confirmed to be working, I'll close this issue; There are some additional things to be added in the future (like making use of bitflags, for example), but I can always reopen this later or start a new issue when the time comes.
