### ISSUE TITLE
created two plugins ;)

### ISSUE THREAD

**Issue by mtrefzer** [phpMussel/phpMussel#100]
I created two plugins for phpMussel
- [mtrefzer/plugin-log2mysql](https://github.com/mtrefzer/plugin-log2mysql)
- [mtrefzer/plugin-resultAsJson](https://github.com/mtrefzer/plugin-resultAsJson)

**Comment by Maikuolan** [comment]
Very cool! That is fantastic. :-)

I'll add them to the list; They definitely look useful, and the contributions are much appreciated. :+1:
