### ISSUE TITLE
How to connect phpMussel with WordPress?

### ISSUE THREAD

**Issue by matteoraggi** [phpMussel/phpMussel#107]
Ok, I know that I have to insert this code 

``` php
<?php require '/user_name/public_html/phpmussel/phpmussel.php'; ?>
```

into my CMS, and where it is better to insert it in wordpress? footer? index,.php ? functions.php ? or where?
Why don't launch it externally to scan the files? I have dozens of websites to control.. it mean that I should change the code into every single website?

**Comment by DanielRuf** [comment]
This code should be in wp-config.php to prevent that it is overridden and removed by updates.

Or you use the code for .htaccess or your php.ini (see readme for the exact code).

You can also install phpMussel using Composer and requiring the generated autoload file.

**Comment by matteoraggi** [comment]
I am not a developer, but inserting this line 
`<?php require '/myusername/public_html/pphmussellino/phpmussel.php'; ?>`
in the line 4 of the wp-config.php , then I receive this error:

> Parse error: syntax error, unexpected '<' in /myusername/public_html/eforte.it/wp-config.php on line 4

**Comment by DanielRuf** [comment]
You should just insert this

``` php
require '/myusername/public_html/pphmussellino/phpmussel.php'; 
```

**Comment by matteoraggi** [comment]
thanks it don't give error! and how to read if there are some malware or viruses then?

**Comment by DanielRuf** [comment]
@matteoraggi phpMussel generates some logfiles like scan_kills.txt (blocked uploads), scan_log.txt (all scanned uploads) and scan_log_serialized.

See https://github.com/Maikuolan/phpMussel/blob/9607dcb1504f8cee54ea0d91430f0f0e055077b2/vault/phpmussel.ini#L27-L48

For an overview of the generated and available files which are there by default take a look at the table here https://github.com/Maikuolan/phpMussel/blob/93e5c6a795c533cf828c85e95dbb06a20c93bad0/_docs/readme.en.md#5-files-included-in-this-package

```
※ /vault/scan_kills.txt   A record of every file upload blocked/killed by phpMussel.
※ /vault/scan_log.txt A record of everything scanned by phpMussel.
※ /vault/scan_log_serialized.txt  A record of everything scanned by phpMussel.
```

**Comment by matteoraggi** [comment]
Thanks! but I can't find these files into the vault folder and I am usign the default .ini file.
 these fiels are not being created: 

> /vault/scan_kills.txt   /vault/scan_log.txt  /vault/scan_log_serialized.txt 

 and the vault folder has 777 permissions.

**Comment by DanielRuf** [comment]
Is the folder recursively set to `chmod 777` so phpMussel can create the files on your server?

**Comment by matteoraggi** [comment]
no, it wasn't now it is , thanks! should I apply it to only the folder or also the files?

**Comment by DanielRuf** [comment]
Maybe also to the files as unfortunately your hosting needs these permissions on the files. But you have to test it. As few as possible files and folders should have `chmod 777`.

**Comment by matteoraggi** [comment]
Ok, thanks and into how much time these files should be created after surfing on the protected website?

**Comment by DanielRuf** [comment]
Normally when the first upload is scanned by phpMussel afaik.

**Comment by DanielRuf** [comment]
As the integration works now I'm closing this issue. Please consult the documentation for further information and the ini file.
