### ISSUE TITLE
why check only the uploaded files?

### ISSUE THREAD

**Issue by matteoraggi** [phpMussel/phpMussel#108]
Why check only the uploaded files? Is there a way or another free software checking the files on the webserver trough ClamAv?

**Comment by DanielRuf** [comment]
phpMussel just uses signatures from the ClamAV project. phpMussel does not run ClamAV. You can manually run a scan with phpMussel with the following code

``` php
 $results = $phpMussel['Scan']('/user_name/public_html/my_file.html', true, true);
 echo $results;
```

see https://github.com/Maikuolan/phpMussel/blob/master/_docs/readme.en.md#SECTION3A and https://github.com/Maikuolan/phpMussel/blob/master/_docs/readme.en.md#SECTION3B

If you have a root server you can use any available solution, for example there are shell scripts which can scan files, for example over SSH.

Generally speaking it makes no sense to scan all files every time someone accesses an URL as this is not good for the performance. Just uploaded files configured in the ini file (filesize, mimetype, file extension, ...) are scanned.

If you want to monitor your server for changes take a look at https://github.com/DanielRuf/SSAM/tree/ssam158 and other solutions. If a file is changed, you can further inspect it and start a scan on the server with a custom script.

**Comment by matteoraggi** [comment]
I just create a file named for example runclamav.php and inside it I write 

```
$results = $phpMussel['Scan']('/user_name/public_html/my_file.html', true, true);
 echo $results;
```

right? I'm not able to use SSH.
I just want to do one complete scan and maybe repeat it one time monthly or yearly to feel sure in the case if uploading a virus the AV was not enough updated..

**Comment by DanielRuf** [comment]
phpMussel is not ClamAV and does not run any binary version of ClamAV, just for your information.

First you have to `require` or `include` phpMussel and change some settings in the ini file

> However, you're also able to instruct phpMussel to scan specific files, directories and/or archives. To do this, firstly, you'll need to ensure that the appropriate configuration is set in the phpmussel.ini file (cleanup must be disabled), and when done, in a PHP file that's hooked to phpMussel, use the following closure in your code:

**Comment by Maikuolan** [comment]
> I just create a file named for example runclamav.php and inside it I write 
> 
> ```
> $results = $phpMussel['Scan']('/user_name/public_html/my_file.html', true, true);
>  echo $results;
> ```
> 
> right? I'm not able to use SSH.
> I just want to do one complete scan and maybe repeat it one time monthly or yearly to feel sure in the case if uploading a virus the AV was not enough updated.. 

That should work correctly (in regards to being able to scan monthly, yearly, etc). :-)

If the number of files to be scanned are small, then enabling the Virus Total API options may be useful, also (due to that this will increase the chances of detecting infected files). If the number of files to be scanned are large though, then it's possible the quota limits for the Virus Total API may be reached quickly (and so, might provide very minimal benefit).

Checking out SSAM would definitely be a great idea, too; SSAM will allow you to compare files over time, to see whether any unauthorised changes have occurred (which can be a strong indicator of a possible infection, and isn't something that phpMussel is currently capable of doing).

(Edit: AFAIK, at least. @DanielRuf I spotted that on the to-do list a while back, but I haven't tested it or checked it recently. Has that been implemented to SSAM?).

**Comment by Maikuolan** [comment]
(PS, I think I might modify the third paragraph under Section3B; "On-the-fly" is probably a bit too vague a term to use, I think. I'll mention something about on-demand versus on-access in the next documentation commit).

**Comment by DanielRuf** [comment]
> chances of detecting infected files

If they were scanned by VirusTotal before. We just check the available results from them.

**Comment by DanielRuf** [comment]
> @DanielRuf I spotted that on the to-do list a while back, but I haven't tested it or checked it recently. Has that been implemented to SSAM?)

@Maikuolan What exactly? So far I did not find the time to work on the current master branch.

**Comment by ad-wade** [comment]
> Checking out SSAM would definitely be a great idea, too; SSAM will allow you to compare files over time, to see whether any unauthorised changes have occurred (which can be a strong indicator of a possible infection, and isn't something that phpMussel is currently capable of doing).

When I tried to search for it (on github), I got:  "We couldn’t find any code matching 'ssam'"

What is it and where can I find it?

**Comment by DanielRuf** [comment]
@ad-wade you have to search for the repository name. I linked it here in a comnent in this issue, the link is https://github.com/DanielRuf/SSAM/tree/ssam158 which you will also find on https://websectools.com/#monitoring-scripts

**Comment by ad-wade** [comment]
Thanxx!

**Comment by Maikuolan** [comment]
> @Maikuolan What exactly? So far I did not find the time to work on the current master branch.

(Regarding checking for changes made to files over time).

I think this issue is probably resolved now anyhow. Shall we close it?

**Comment by DanielRuf** [comment]
@Maikuolan SSAM, the original version, already tracks changes. My master version is just a fork and rewrite which should be more secure, better, and so on.

**Comment by Maikuolan** [comment]
Awesome! Reinforces our suggestions in that case, that it would be a great way to check for possible infections (via unauthorised file modifications and such). :-)

**Comment by Maikuolan** [comment]
_Closing and marking as resolved. Will reopen upon request by OP._
