### ISSUE TITLE
config detect_deface=false has no effect

### ISSUE THREAD

**Issue by mtrefzer** [phpMussel/phpMussel#113]
I switched detect_deface in my config to false, but I still get "Detected phpMussel-Graphics.Defacement.X-01" scan Results.

Cheers Michael

**Comment by Maikuolan** [comment]
It could be a caching issue, possibly.

I've just tested the codebase locally, and from an empty cache, I couldn't replicate the problem; Though, scanning first with `detect_deface=true`, and then switching to `detect_deface=false` and scanning again, caused the problem to appear.

Possibly may need to empty the cache after changing some configuration options in some cases. Check to see whether a file `/vault/cache/48.tmp` exists; If it does, try deleting it, and then scanning again.

Let me know the results. :-)

**Comment by Maikuolan** [comment]
[![test](https://cloud.githubusercontent.com/assets/12571108/19750358/0e068122-9c23-11e6-9d27-4eb9cd15c007.gif)] <-- Small GIF image, containing "r00t" in the comment; This should trigger the signature in question (useful for testing this specific signature).

**Comment by mtrefzer** [comment]
After removing the file `/vault/cache/48.tmp` the defacement checks where ignored.
Thanks mate :-) You made my day

**Comment by Maikuolan** [comment]
Awesome. :-)
