### ISSUE TITLE
Error loading phpmussel

### ISSUE THREAD

**Issue by msouzarunner** [phpMussel/phpMussel#122]
Please use this template when reporting bugs, problems, issues, etc.

### phpMussel version used (if known, please also include the exact commit hash).
eg 1.0.0-DEV@c8778924df2cb94d40796a0876005c46b711e76e

### PHP SAPI used (`<?php echo php_sapi_name(); ?>`).
srv

### PHP version installed (`<?php echo phpversion(); ?>`).
7.1.0

### Operating system used (`<?php echo php_uname(); ?>`).
Linux 4.7.0-040700-lowlatency #201608021801 SMP PREEMPT Tue Aug 2 22:07:01 UTC 2016 x86_64
---
## Issue
Please describe the problem here.
Cannot create phar '//tmp/mUnoMI', file extension (or combination) not recognised or the directory does not exist

### Expected behavior
What should normally happen?
Go without error

### Actual behavior
What is actually happening?
error
Even though set to cleanup = false
I already checked the permissions on the / tmp folder

### Steps to reproduce the behavior

include_once(ABSPATH.'_classes/phpMussel-master/phpmussel.php');

### Last known working version without this issue.
---

**Comment by DanielRuf** [comment]
How did you install phpMussel? Did you use composer or something else?

Any verbose information?

**Comment by msouzarunner** [comment]
Yes, I used the composer.

**Comment by msouzarunner** [comment]
How can I change the / tmp folder in the phpmussel configuration.

**Comment by DanielRuf** [comment]
This is the tmp folder of your syste where files are processed/scanned.

**Comment by DanielRuf** [comment]
Did you try setting chown of the files in `_classes/phpMussel-master`?

**Comment by DanielRuf** [comment]
This is the tmp folder of your system where files are processed/scanned.

Did you try setting chown of the files in `_classes/phpMussel-master`?

When did this exactly happen? Just after setting the include or doing more?

**Comment by msouzarunner** [comment]
All external libs or api I put in this folder

**Comment by msouzarunner** [comment]
When I load via include the phpmussel

**Comment by msouzarunner** [comment]
Was working in the /var/www/html folder, there I created a virtualhost in /var/www/domain.com/public_html. That's where it stopped

**Comment by msouzarunner** [comment]
So I think I have to change the / tmp folder to process inside /var/www/tickets.com/public_html/tmp

**Comment by msouzarunner** [comment]
Phpmussel is not seeing the / tmp folder outside of virtualhost.

**Comment by DanielRuf** [comment]
Sounds like open_basedir / permission (chown) related things. Phar extension is available and enabled?
Seems so to me.

What would you say @Maikuolan ?

**Comment by msouzarunner** [comment]
Oops, I'll see about phar extension

**Comment by DanielRuf** [comment]
Not sure where this phar file is generated. An anonymized stacktrace (errorlog) would be helpful to see which line triggers this exception.

Was this the complete error message?

**Comment by msouzarunner** [comment]
I'll see if you found anything in the logs.

**Comment by msouzarunner** [comment]
The phar extension is installed

**Comment by msouzarunner** [comment]
I discovered the problem, when I call phpmussell via ajax/post it puts a // in the //tmp folder, if you can verify this.

**Comment by Maikuolan** [comment]
I'll do some testing within the next few hours to attempt to replicate the problem.

**Comment by msouzarunner** [comment]
Thank you for your attention.

**Comment by DanielRuf** [comment]
Can you show us the code how you call / execute phpMussel?

Generally multiple forward slashes should not be a problem.

**Comment by DanielRuf** [comment]
See https://3v4l.org/bqI6p

Further information would be helpful.

**Comment by msouzarunner** [comment]
I have a download demo including phpmussel, I'll send you the download link

**Comment by Maikuolan** [comment]
Sorry for the delays in replying. Had a headache earlier and had to rest for a while. Haven't done any testing yet but will do so tonight.

**Comment by msouzarunner** [comment]
I did what was indicated and everything is fine, the folder is writable and being located.

**Comment by msouzarunner** [comment]
No problem, I'm trying to sort it by looking at your code.

**Comment by msouzarunner** [comment]
I made a template for download using phpmussel, see if it works there with you : *DanielRuf: I've removed the link and sent it to @Maikuolan*

**Comment by msouzarunner** [comment]
Here to me gives the following error: Cannot create phar '//tmp/ZA4t7t', file extension (or combination) not recognised or the directory does not exist

**Comment by msouzarunner** [comment]
I did the following test, I changed the tmp folder in the php.ini file, like this:
upload_tmp_dir = /var/www/tickets.com/public_html/tmp

To search inside my virtualhost and still give the same problem.

**Comment by msouzarunner** [comment]
Then I changed the first one '/' leaving it like this:
upload_tmp_dir = var/www/tickets.com/public_html/tmp

Then the problem stopped in phpmussel, and started downloading the file in the tmp folder, because I could not find it for recording.

**Comment by DanielRuf** [comment]
Sounds like a path issue @Maikuolan

/var/… is absolute and var/… is relative, big difference.

**Comment by msouzarunner** [comment]
Yes, I did this just to test and see if I could define the problem.

**Comment by msouzarunner** [comment]
I did another test on a vm ubuntu 14.04, only with apache2 and php5 and it worked. When I install the problem's HHVM in the TMP folder.

So even in vm ubuntu 16.04 with apache2, php7 and hhvm 3.18, the problem because of HHVM.

**Comment by DanielRuf** [comment]
You mean HipHop VM? I'm not sure how this affects the code. So far we did not check the code with unit tests and a virtual filesystem using HHVM so we could possibly need more details about the full stacktrace of the error to see where it is caused.

I'm not a HHVM user and I did not follow their development and how far they are compatible with PHP (5/7) code.

**Comment by msouzarunner** [comment]
VM HHVM is equal to Virtual Machine with HHVM, in my case a VM with HHVM comes working with everything, the only thing I noticed I'm going this adjustment I made in php.ini and changed the behavior of phpmussel.

**Comment by msouzarunner** [comment]
HHVM changes the behavior of php 7 because it takes control of everything, perhaps this is a small detail regarding the function that returns the name of the operating system tmp folder.

**Comment by msouzarunner** [comment]
I'm using virtualbox to upload my vm's and test the whole process before moving to a server in production.

**Comment by DanielRuf** [comment]
> the only thing I noticed I'm going this adjustment I made in php.ini and changed the behavior of phpmussel.

What adjustment do you mean?

**Comment by msouzarunner** [comment]
Did you get the example I told you to do?

**Comment by DanielRuf** [comment]
> Did you get the example I told you to do?

Yes, I sent it to @Maikuolan

**Comment by msouzarunner** [comment]
I also discovered that the problem only happens when I use ajax / post calling the php script that includes phpmussel. If I call directly via browser the php script works. Even using HHVM.

**Comment by DanielRuf** [comment]
> I also discovered that the problem only happens when I use ajax / post calling the php script that includes phpmussel. If I call directly via browser the php script works. Even using HHVM.

My guess was also that it might be an AJAX issue. Let's see what @Maikuolan found when he feels better. Unfortunatelx I do not have so much time this week for full tests.

**Comment by msouzarunner** [comment]
Is there another way to scan the uploaded file?

**Comment by DanielRuf** [comment]
Sure. If you hook phpmussel.php using `php_value auto_prepend_file` or something else, phpMussel will scan all file uploads in `$_FILES` on each request before it is processed by other scripts.

**Comment by msouzarunner** [comment]
I will try here !

**Comment by Maikuolan** [comment]
Yep, received. :-)

I've looked at the package you've sent us, and when testing it in my own environment, I'm also getting a number of errors, but it seems to be a different set of errors than the errors you're seeing in your environment. Digging through it a little deeper at the moment to try to figure out the best solution.

**Comment by msouzarunner** [comment]
Thanks for the attention, I really hope I can use phpmussel. It works perfect in php 5, but I had to upgrade to php7 and include HHVM to improve the performance of my application.

**Comment by msouzarunner** [comment]
I mounted a new VM with Ubuntu 16.04 and PHP7, and I tested it with the routine I sent and it worked. The problem and even with HHVM, I think it does not have all the modules that PHP7.

**Comment by mtrefzer** [comment]
Perhaps of topic, but I'm actually always reading "mounted new VM" or "changes in php.ini", just try out docker for virtualization and ready configured setups to test against. It might be easier to figure out the problem.

**Comment by DanielRuf** [comment]
> I mounted a new VM with Ubuntu 16.04 and PHP7, and I tested it with the routine I sent and it worked. The problem and even with HHVM, I think it does not have all the modules that PHP7.

@msouzarunner Sure, HHVM is a replacement / alternative to PHP but not exactly the same, it is an own VM officially supports their Hack language and was made for this, also PHP5 and major parts of PHP7 but not fully PHP7. We do not officially support or test HHVM.

http://hhvm.com/
> HHVM supports Hack, PHP 5 and the major features of PHP 7. We are aware of minor incompatibilities, so please open issues when you find them. HHVM also supports many extensions as well.

Take a look at the following links:

http://hhvm.com/blog/10859/php-7-support  
> The INI option hhvm.php7.all = 1 enables the PHP 7 behavior for backwards-incompatible changes. (PHP 5 behavior will remain the default still for a while.) Each major compatibility break has its own option, if you want to turn them on one by one. See our INI documentation for details.

https://github.com/facebook/hhvm/issues?q=is%3Aopen+is%3Aissue+label%3A%22php5+incompatibility%22  

https://github.com/facebook/hhvm/issues?q=is%3Aopen+is%3Aissue+label%3A%22php7+incompatibility%22  

Just throwing HHVM and other things you don't know into one VM does not solve but create new problems.

Why not caching and solutions like Varnish, Memcached, Nginx and other alternatives and better hardware. A VM does not provide the performance of a real root server.

I think we can close this issue now as it seems it is just an issue with HHVM.

**Comment by DanielRuf** [comment]
> Perhaps of topic, but I'm actually always reading "mounted new VM" or "changes in php.ini", just try out docker for virtualization and ready configured setups to test against. It might be easier to figure out the problem.

@mtrefzer Same here. If he does not know Docker, better not use it. We did not test phpMussel with HHVM in a VM or in a container using Docker. phpMussel was created with managed hosting environments in the mind. If you have a root server or a VM which provides the same permissions, you have access to much stronger and better scanners which run on the system level, not the application level, and are independent of the language the project is written in (DrWeb, ClamAV - phpMussel uses many ClamAV signatures, and others).

**Comment by mtrefzer** [comment]
@DanielRuf agreed and 
Cheers ;)

**Comment by Maikuolan** [comment]
@DanielRuf  @msouzarunner Considering the above, should I mark this issue as "resolved"?

**Comment by msouzarunner** [comment]
Sorry for my insistence, but I managed to run phpmussel with php7 + hhvm on ubuntu 16.04. The solution was to not execute the upload.php script, this way it scans and if it has a virus it aborts the upload of the file.

**Comment by Maikuolan** [comment]
Awesome. :-)

Glad to hear the issue has been resolved.

(On a side note: Although not quite ready yet, there's a significant number of changes which'll be introduced when the "unstable" branch is eventually ready to be merged back to master; Hopefully everything will run a bit more smoothly when that happens in the not too distant future).
