### ISSUE TITLE
Error in phpMussel

### ISSUE THREAD

**Issue by wajdijurry** [phpMussel/phpMussel#127]
In phpMussel v0.10.0, this errors occurred while trying to upload some files, the scanning process stuck because of this erros:

PHP Warning:  reset() expects parameter 1 to be array, string given in /phpmussel/vault/upload.inc on line 444

PHP Warning:  key() expects parameter 1 to be array, string given in /phpmussel/vault/upload.inc on line 451

PHP Notice:  String offset cast occurred in /phpmussel/vault/upload.inc on line 452

PHP Notice:  Uninitialized string offset: 0 in /phpmussel/vault/upload.inc on line 452

PHP Warning:  next() expects parameter 1 to be array, string given in /phpmussel/vault/upload.inc on line 456

PHP Warning:  implode(): Invalid arguments passed in /phpmussel/vault/upload.inc on line 458

**Comment by DanielRuf** [comment]
Please provide more info about your environment and use the issue template.

Which PHP version do you use?

**Comment by DanielRuf** [comment]
Is the cache directory writeable?

Try changing `reset($phpMussel['HashCache']['Data']);` to `exit($phpMussel['HashCache']['Data']);` at https://github.com/Maikuolan/phpMussel/blob/d96f9378bebc5b621ab0f0704e5358b7962d479d/vault/upload.inc#L444 for further debbuging.
What do you see after a new upload?

@Maikuolan https://github.com/Maikuolan/phpMussel/blob/d96f9378bebc5b621ab0f0704e5358b7962d479d/vault/upload.inc#L444

https://github.com/Maikuolan/phpMussel/blob/d96f9378bebc5b621ab0f0704e5358b7962d479d/vault/functions.inc#L750-L754

**Comment by wajdijurry** [comment]
Some times when trying to upload files (such as , it returns that errors. It is not clear why this type of errors appear.

**Comment by DanielRuf** [comment]
Did you test the given code `exit...`? Please test it with this and try to reproduce it, copy the displayed results (they should differ, array and some "string") and show it to us.

**Comment by wajdijurry** [comment]
I think the error was that sometimes the phpmussel function receives empty file array, so it prints like error in error log.

Thanks for supporting.

**Comment by DanielRuf** [comment]
That should be the case if there are upload errors. Please check your code and the config option `ignore_upload_errors` and see https://github.com/Maikuolan/phpMussel/blob/master/vault/upload.php#L30-L33

**Comment by DanielRuf** [comment]
@Maikuolan at least the warnings and notices should not be there,
