### ISSUE TITLE
When can 1.0.0 be expected?

### ISSUE THREAD

**Issue by senky** [phpMussel/phpMussel#130]
Hello,
sorry for this issue, but I have found no other way to contact you. I can see from the code inspection, that v1.0.0 is near to be released and breaks compatibility with 0.10.0. What is the estimated time for 1.0.0 to be released? Maybe I can wait for a month or so...

**Comment by DanielRuf** [comment]
Please see https://github.com/Maikuolan/phpMussel/issues/82

**Comment by Maikuolan** [comment]
Also, although not originally intended for discussing the `v1.0.0` release date, this issue does cover that subject somewhat in subsequent replies: https://github.com/Maikuolan/phpMussel/issues/124
