### ISSUE TITLE
transfer to organization

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#131]
https://help.github.com/articles/about-repository-transfers/
https://github.com/composer/packagist/issues/47

- [x] fork repo to the org and disable PRs and issues
- [x] generate new GitHub pages
- [x] change GitHub paths in composer.json and other files
- [x] update links where needed
- [x] submit the new package to packagist / composer
- [x] update hooks and services if any are set (the original repo should get the settings of the new one)
- [x] delete org repo, transfer original repo to org

Currently collecting. Add any additional steps which you think are needed. I would suggest starting transition and first preparation in the next 3 months (Juni - Aug) and the final step with the transfer after this.

Will try to find and onboard some more developers (and get more licenses from IntelliJ) and would probably donate some test instance (can run Git on my server and write some script for testing purposes).

Any feedback is very welcome.

**Comment by Maikuolan** [comment]
+1.

Transferring to the organisation is something I've liked the idea of doing for a while now. My main hesitation about it has been the risk of accidentally breaking anything, how to get it to work properly with composer/packagist/etc.

It makes more sense for the package to exist as part of the organisation in the long run, and looks more professional that way, as opposed to simply being on my account and outside the organisation. I just don't want anything to break, if breaking anything can be avoided. :-)

There are some other external services that the package is also tied into (e.g., SourceForge), but these should be quite easy to adjust (I think it's just a matter of changing a few webhooks and that's it).

3 months sounds like a good target, IMO.

**Comment by Maikuolan** [comment]
(I'll begin working on this tomorrow afternoon).

**Comment by DanielRuf** [comment]
No hurry =)

For phpMussel we should probably plan it a bit more as you might have to update other external repositories and links (might be more than in the case of CIDRAM).

**Comment by Maikuolan** [comment]
True (and I suspect that there probably will be quite a bit more).

Forking the repo and generating some new GitHub pages shouldn't be too difficult though; That should be safe to make a start on. But yeah, I agree; Planning it out a bit more would be good.

**Comment by Maikuolan** [comment]
- New GitHub pages have been generated.
- All necessary internal changes have been made, and are currently sitting in temporary patch branches (haven't yet merged to master on the main repo; have merged to master on the fork, and so far, no problems, and seems good). Will merge when ready to do the swap.
- GitHub paths adjusted via temporary patch branches; Will mark it as done after the merge to master has been done.

**Comment by Maikuolan** [comment]
All items on the list completed. Double-checking everything first, in case I missed anything, but so far, seems good.

(Re-forked the parent back to my account after transferring; In case of missing anything, links, integrations, etc, project should still be accessible).

**Comment by Maikuolan** [comment]
Can't see any problems. Marking as implemented and closing. Will reopen if any relevant future problems emerge.
