### ISSUE TITLE
Possible compatible problem for PHP 7.2.x

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#134]
*See: https://wiki.php.net/rfc/release-md5-deprecation*

MD5 support is currently required by phpMussel in order to be able to process the PE sectional and MD5 hash-based signatures from ClamAV. Continued supported for these signatures from ClamAV requires that PHP continue to support MD5, which currently looks to be voted for deprecation, potentially as early as PHP 7.2.0.

*Worth noting though that the current latest version of PHP is PHP 7.1.6, and so, this issue explores a future compatible problem, rather than a current compatibility problem. Users need not be alarmed.*

Additionally, phpMussel uses MD5 hashes as references to scanned items in the scan logs, although this is somewhat less integral to phpMussel as a whole (it's simple enough to switch from MD5 to something else as far as the scan logs are concerned).

In the event that this compatible problem comes to pass, and assuming that ClamAV continues to use MD5 for its signatures database, the two most obvious solutions for dealing with this problem, as far as I see it, are:
1. Just drop support for MD5 from phpMussel entirely, too (which would also mean dropping support for PE sectional signatures, MD5 hash-based signatures, and changing the way that scan logs reference scan events; not so keen on doing this, because that would mean dropping support for quite a large chunk of the overall ClamAV signatures database, and to some extent, would bring into question the overall continued usefulness of phpMussel as a package).
2. Write some MD5 polyfills for phpMussel, to allow it to continue to support MD5 (I know, other developers hate this, other developers often recommend against writing polyfills for crytographic and hashing algorithms, as well as rally against using MD5 for anything and so on, but if PHP drops support for it entirely and ClamAV continues to use it for signatures, polyfills seems the only viable way to continue to allow phpMussel to support those signatures, AFAIK).

This would probably also affect plans for any future tools for automating the process of cutting new signature sets too, I guess (e.g., whether it does or doesn't bother with these types of signatures).

*PS, I totally get why developers rally against it. For cryptographic purposes, password management, etc, I'm not any different in that regard, and I would NEVER recommend using it for cryptography or password management! It is broken and it is easy to generate collisions for it (which is also one of the reasons why it isn't too great for hashing files for that matter, either). However, that doesn't change the fact that ClamAV is still using it for signatures at the moment.*

**Comment by DanielRuf** [comment]
They just mean the md5 checksum hashes for the PHP releases, not the md5 support in PHP.

See https://github.com/php/web-php/compare/master...sgolemon:md5-deprecation

**Comment by Maikuolan** [comment]
I guess, the RFC does sound like that's what it's about, and hopefully that's the case. To that extent, and for what it's worth, I would agree with the voters, too; I don't see any real need anymore to continue maintaining MD5 checksums in the releases themselves. Due to the context in how I found out about this RFC (a discussion at Facebook which involved the subject of MD5) and due to that some of the people involved in that discussion were talking about the possibility of MD5 support being dropped from PHP, I'd thought that the RFC might've been referring to that.

Oh well. I guess I'll close this issue then, in that case.
