### ISSUE TITLE
Quarantine

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#142]
So, I've been thinking about whether I should add a quarantine page to the phpMussel front-end. The general idea would be to provide a page whereby users could see what's sitting in their quarantine (technically already possible via the file manager, due to that the file manager can view everything in the vault, but everything is mixed in together, so it might be difficult to distinguish quarantine files from other files for users that don't know any better), and optionally (possibly), restore quarantined files to their original state for download.

Possible downsides:
- Might provide a temptation for non-savvy users to restore dangerous files when they shouldn't do so.
- Might ultimately be a pointless task, if nobody ever uses it anyhow (TBH, I'm not sure how many users would actually take advantage of it).

Possible upsides:
- Might make the front-end feel more "complete", in the sense that most AV tend to provide similar functionality already anyhow (i.e., the ability to restore quarantined files), and providing that ability to phpMussel might bring it into greater conformity with those other AV.
- Provides an opportunity for (somewhat slightly more) convenient restoration in the event of false positives (although this is already reasonably easy to do manually.. it just isn't yet possible specifically via the front-end).
- Provides an opportunity for (somewhat slightly more) convenient analysis of quarantined files (although this is already reasonably easy to do manually.. it just isn't yet possible specifically via the front-end).
- Should be extremely easy to implement (I could probably finish coding it all up in a day or two at the most I reckon, if I was to make a start on it).

Thoughts? For/Against..?

**Comment by ad-wade** [comment]
As a bona-fide, non-savvy user of phpMussel, I can tell you that I don't 
think 'I' would ever restore a quarantined file in error.  I'm just too 
careful and leery of unsure things, but I certainly understand your 
point. That said...

Personally, yes I'd like to see a quarantined files page, as it would 
help me to keep up with such and investigate who uploaded it.
*A.D. Wade*
------------------------------------------------------------------------

**Comment by Maikuolan** [comment]
Thanks for the response. I'm glad to be able to hear from someone about this issue, as it is something I've had difficulty coming to a final decision about. :-)

I've decided to go ahead and implement the quarantine. If all goes well, work should be completed within the next day or so.

**Comment by Maikuolan** [comment]
All done. :+1:
