### ISSUE TITLE
simple deployment for testing environment

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#16]
This issue is created as a reminder for me to create a script to automatically deploy the latest version of phpMussel from the repository.

This might be the first or an useful addition for a future installer.

For reference: https://github.com/Maikuolan/phpMussel/pull/14#issue-81842138

**Comment by DanielRuf** [comment]
@Maikuolan I've prepared a special subaccount on my hosting account for testing purposes (only for you as some security restrictions were removed).

Can you send me a PGP signed mail with your public key to the emailaddress on my website?
Then I will send you the credentials for this account and more information so you can test there.

Is this ok?

**Comment by Maikuolan** [comment]
@DanielRuf Yeah, that should be okay. Might not be tonight though, because I'll need to get a PGP key sorted out for myself (been meaning to do so for a while, but hadn't yet gotten around to getting myself a PGP key). Some time over the weekend though..? And cheers. :-)

**Comment by DanielRuf** [comment]
Great. I will prepare all information that you will need.
Let me know when you have the PGP key.

That's no problem. Have a great weekend.

**Comment by Maikuolan** [comment]
@DanielRuf I've managed to figure out how to create a PGP key for myself and integrate it with my email software (hopefully I've done it correctly; it's my first time); I've tried sending you an encrypted+signed email just now, and I -think- I've done it correctly, but not I'm not entirely sure. Let me know if seems to have come through or if there are any problems with it. :-)

**Comment by DanielRuf** [comment]
@Maikuolan Got your mail and could read it without any problems. You have an answer ;-)

An expiration date for the PGP key is sometimes useful but not required.

So far the PGP key is correct / valid and sending encrypted mails to you works without any problems.
Please let me know if you can read / decrypt my answer.

**Comment by Maikuolan** [comment]
@DanielRuf Yep, received your reply. It seems to be working correctly. :+1:

**Comment by DanielRuf** [comment]
@Maikuolan Great. 
Can I close this issue or should I let it open as a reminder for a future deployment solution or installer?

**Comment by DanielRuf** [comment]
@Maikuolan Great. 
Can I close this issue or should I let it open as a reminder for a future deployment solution or installer?

You have a new mail, made a mistake in the mail before.

**Comment by Maikuolan** [comment]
It should be fine to close. :-)
