### ISSUE TITLE
Cannot reset default admin password

### ISSUE THREAD

**Issue by webtent** [phpMussel/phpMussel#161]
Forgot to mention under an earlier issue post, I have not been able to reset the admin default password. On FreeBSD 11.1 using PHP 7, I enable the Frontend and try to reset the password on first login. When I setup on our development server, I just created a new user with complete access and then login as the new user and deleted the admin, then re-created with the password I wanted.

Now trying to setup on our production server, I am even unable to delete the admin after creating and logging in with a new user with complete access. When I look in the browser console, I see this error when clicking on the `OK` button with `Delete account` selected:

`Uncaught ReferenceError: acc is not defined
    at HTMLInputElement.onclick (loader.php?phpmussel-page=accounts:81)
onclick @ loader.php?phpmussel-page=accounts:81`

**Comment by Maikuolan** [comment]
Investigating now.

**Comment by Maikuolan** [comment]
Small typo introduced to one of the JavaScript functions on the accounts page during a recent refactoring. Fixing now.

**Comment by Maikuolan** [comment]
Done. :-)

Thanks for reporting this. Updating to the latest commit should resolve the problem.
