### ISSUE TITLE
Slow scanning

### ISSUE THREAD

**Issue by cwolcott** [phpMussel/phpMussel#168]
### phpMussel version used
name : phpmussel/phpmussel
version: v1.2.0
source : {
type : git
url : https://github.com/phpMussel/phpMussel.git
reference : [4c4d1ff](https://github.com/phpMussel/phpMussel/commit/4c4d1ff541bccc16598309f16fdfead13ddce568)

### Signatures version
All signature files downloaded and extracted from:
https://github.com/phpMussel/Signatures/tree/master/clamav
No other signatures used

### PHP SAPI used
apache2handler

### PHP version installed
PHP 7.0.30

### PHP configuration
memory_limit increased to 4096M from 128M

### Operating system used
Linux 4.4.0-104-generic
Ubuntu 16.04.1 x86_64
Zend Engine v3.0.0 with Zend OPcache

# Issue
This is not a fair question, but lets see if there are any suggestions.  We are experiencing an extreme slow down scanning files on several of our servers compared to our production server. 

All of the php.ini files are the same.  We don't touch phpMussel config.php file.  I need to look at apache configuration, but I am not sure how that would affect phpMussel.  Does anyone have a suggestion were to look next.

I have executed this script on 5 different servers.
```
<?php
require $_SERVER['DOCUMENT_ROOT'] . '/vendor/autoload.php';
require $_SERVER['DOCUMENT_ROOT'] . '/core/bootstrap.php';
require $_SERVER['DOCUMENT_ROOT'] . '/vendor/phpmussel/phpmussel/loader.php';

$phpMussel['Config']['files']['filesize_limit'] = '100KB'; // '1KB', '5MB';
$phpMussel['Config']['files']['filesize_response'] = false; // [true - Blacklist] or [false - Whitelist];

$fileArray = [
    'file0' => "{$_SERVER['DOCUMENT_ROOT']}/SmallContents10a.pdf",   // 85KB
    'file1' => "{$_SERVER['DOCUMENT_ROOT']}/SmallContents10b.pdf",   // 85KB
    'file2' => "{$_SERVER['DOCUMENT_ROOT']}/eicar.txt",
];

\\$phpMussel['Set-Scan-Debug-Array']($scanDetails);
foreach ($fileArray as $key => $file)
{
    $results = $phpMussel['Scan']($file, true);
    echo "{$results}<br>";
}
\\dd($scanDetails);
```

On our production server the script executes immediately (1 second):
```
Tue, 11 Sep 2018 17:48:22 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-p/htdocs/SmallContents10a.pdf' (FN: 979787d4; FD: d7fe8327): -> No problems found. Tue, 11 Sep 2018 17:48:22 -0400 Finished. 
Tue, 11 Sep 2018 17:48:22 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-p/htdocs/SmallContents10b.pdf' (FN: d037fd04; FD: d7fe8327): -> No problems found. Tue, 11 Sep 2018 17:48:23 -0400 Finished. 
Tue, 11 Sep 2018 17:48:23 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-p/htdocs/eicar.txt' (FN: 30f11f8a; FD: 1dd02bdb): -> Detected ClamAV-Clamav.Test.File-7! -> Detected phpMussel-Testfile.EICAR.Standard! Tue, 11 Sep 2018 17:48:23 -0400 Finished. 
```

On my development server the script executes slowly (20 seconds):
```
Tue, 11 Sep 2018 17:47:44 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-t/htdocs/SmallContents10a.pdf' (FN: c0f9e505; FD: d7fe8327): -> No problems found. Tue, 11 Sep 2018 17:47:51 -0400 Finished. 
Tue, 11 Sep 2018 17:47:51 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-t/htdocs/SmallContents10b.pdf' (FN: 87599fd5; FD: d7fe8327): -> No problems found. Tue, 11 Sep 2018 17:48:04 -0400 Finished. 
Tue, 11 Sep 2018 17:48:04 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-t/htdocs/eicar.txt' (FN: 3b59c88c; FD: 1dd02bdb): -> Detected ClamAV-Clamav.Test.File-7! -> Detected phpMussel-Testfile.EICAR.Standard! Tue, 11 Sep 2018 17:48:04 -0400 Finished. 
```

On another development server the script executes slowly (24 seconds):
```
Tue, 11 Sep 2018 17:48:41 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-d/htdocs/SmallContents10a.pdf' (FN: 46316800; FD: d7fe8327): -> No problems found. Tue, 11 Sep 2018 17:48:52 -0400 Finished. 
Tue, 11 Sep 2018 17:48:52 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-d/htdocs/SmallContents10b.pdf' (FN: 019112d0; FD: d7fe8327): -> No problems found. Tue, 11 Sep 2018 17:49:05 -0400 Finished. 
Tue, 11 Sep 2018 17:49:05 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-d/htdocs/eicar.txt' (FN: 15fa9494; FD: 1dd02bdb): -> Detected ClamAV-Clamav.Test.File-7! -> Detected phpMussel-Testfile.EICAR.Standard! Tue, 11 Sep 2018 17:49:05 -0400 Finished. 
```

**Comment by DanielRuf** [comment]
Do you have Xdebug or something else installed?

You don't need such high memory_limit settings.

**Comment by DanielRuf** [comment]
https://github.com/brettalton/phpinfo-compare may be useful.

**Comment by cwolcott** [comment]
Yea we compared the php.ini files, no major differences.  I am going to ask the IT group of differences between our development and production servers.

I was hoping that you or @Maikuolan might have any hints as to way a scan on a small pdf files (85KB) might run slow.  I will try other files types to see if there is a slow down.

**Comment by cwolcott** [comment]
Interesting txt and xlsx files of 85KB scan immediately, but the 2 small pdfs scan slow on the development server, but not on our production server.  I will try a couple of other pdf files.

## Development Server
#### TXT (Immediate Scans)
```
Tue, 11 Sep 2018 19:56:35 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-d02/htdocs/SmallContent01a.xlsx' (FN: 900be621; FD: 08f3a13e): -> No problems found. Tue, 11 Sep 2018 19:56:35 -0400 Finished. 
Tue, 11 Sep 2018 19:56:35 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-d02/htdocs/SmallContent01b.xlsx' (FN: 169f948f; FD: 08f3a13e): -> No problems found. Tue, 11 Sep 2018 19:56:36 -0400 Finished. 
Tue, 11 Sep 2018 19:56:36 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-d02/htdocs/eicar.txt' (FN: 52c7c199; FD: 1dd02bdb): -> Detected ClamAV-Clamav.Test.File-7! -> Detected phpMussel-Testfile.EICAR.Standard! Tue, 11 Sep 2018 19:56:36 -0400 Finished. 
```
#### XLSX (Immediate Scans)
```
Tue, 11 Sep 2018 19:58:37 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-d02/htdocs/SmallContent01a.txt' (FN: 02417bc3; FD: a11bcfc8): -> No problems found. Tue, 11 Sep 2018 19:58:37 -0400 Finished. 
Tue, 11 Sep 2018 19:58:37 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-d02/htdocs/SmallContent01b.txt' (FN: 45e10113; FD: 21c8ea46): -> No problems found. Tue, 11 Sep 2018 19:58:37 -0400 Finished. 
Tue, 11 Sep 2018 19:58:37 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-d02/htdocs/eicar.txt' (FN: 52c7c199; FD: 1dd02bdb): -> Detected ClamAV-Clamav.Test.File-7! -> Detected phpMussel-Testfile.EICAR.Standard! Tue, 11 Sep 2018 19:58:37 -0400 Finished. 
```
#### PDFs (Slow Scans)
```
Tue, 11 Sep 2018 19:59:09 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-d02/htdocs/SmallContents10a.pdf' (FN: 2ebe847a; FD: d7fe8327): -> No problems found. Tue, 11 Sep 2018 19:59:16 -0400 Finished. 
Tue, 11 Sep 2018 19:59:16 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-d02/htdocs/SmallContents10b.pdf' (FN: 691efeaa; FD: d7fe8327): -> No problems found. Tue, 11 Sep 2018 19:59:26 -0400 Finished. 
Tue, 11 Sep 2018 19:59:26 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-d02/htdocs/eicar.txt' (FN: 52c7c199; FD: 1dd02bdb): -> Detected ClamAV-Clamav.Test.File-7! -> Detected phpMussel-Testfile.EICAR.Standard! Tue, 11 Sep 2018 19:59:26 -0400 Finished. 
```
## Production Server
#### PDFs (Immediate Scans)
```
Tue, 11 Sep 2018 20:04:02 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-p/htdocs/SmallContents10a.pdf' (FN: 979787d4; FD: d7fe8327): -> No problems found. Tue, 11 Sep 2018 20:04:02 -0400 Finished. 
Tue, 11 Sep 2018 20:04:02 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-p/htdocs/SmallContents10b.pdf' (FN: d037fd04; FD: d7fe8327): -> No problems found. Tue, 11 Sep 2018 20:04:03 -0400 Finished. 
Tue, 11 Sep 2018 20:04:03 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-p/htdocs/eicar.txt' (FN: 30f11f8a; FD: 1dd02bdb): -> Detected ClamAV-Clamav.Test.File-7! -> Detected phpMussel-Testfile.EICAR.Standard! Tue, 11 Sep 2018 20:04:03 -0400 Finished. 
```

**Comment by cwolcott** [comment]
Sorry about all of this.  Here are my final test.  I created a pdf from xlsx (53KB), pdf from ppt (18KB) and a pdf form (17KB).  The previous pdfs were pdf from docs.

## Development Server (The PDF Form is slow, 12 seconds)
```
Tue, 11 Sep 2018 20:51:23 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-d02/htdocs/SmallContent01a.xlsx.pdf' (FN: 36022b49; FD: 4801f85a): -> No problems found. Tue, 11 Sep 2018 20:51:23 -0400 Finished. 
Tue, 11 Sep 2018 20:51:23 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-d02/htdocs/SmallContent01a.ppt.pdf' (FN: b3347ac0; FD: 3fd83e55): -> No problems found. Tue, 11 Sep 2018 20:51:24 -0400 Finished. 
Tue, 11 Sep 2018 20:51:24 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-d02/htdocs/Educational Assistance Request.pdf' (FN: 8ce94dc8; FD: d1e9fa1e): -> No problems found. Tue, 11 Sep 2018 20:51:36 -0400 Finished. 
```

## Production Server (All immediate scans)
```
Tue, 11 Sep 2018 20:51:50 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-p/htdocs/SmallContent01a.xlsx.pdf' (FN: 6f0b6fe5; FD: 4801f85a): -> No problems found. Tue, 11 Sep 2018 20:51:50 -0400 Finished. 
Tue, 11 Sep 2018 20:51:50 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-p/htdocs/SmallContent01a.ppt.pdf' (FN: 094dc1bc; FD: 3fd83e55): -> No problems found. Tue, 11 Sep 2018 20:51:50 -0400 Finished. 
Tue, 11 Sep 2018 20:51:50 -0400 Started. > Checking '/mnt/webrepo/fr-s-sysbio-p/htdocs/Educational Assistance Request.pdf' (FN: 15f142d3; FD: d1e9fa1e): -> No problems found. Tue, 11 Sep 2018 20:51:51 -0400 Finished. 
```

**Comment by Maikuolan** [comment]
Just speculating here, but are all installations using the same versions of the same signature files? If they're using different versions of the signature files, it's possible that there could be some bottleneck in an old signature file version affecting the scan speed for specific types of files or something along those lines. I've noticed that sometimes, when I cut new signature file versions from the ClamAV database, that the target vector for a number of their signatures sometimes moves about from one target vector to another, or there might be significant changes to the actual number of signatures that exist in particular cuts and such. In theory, using different signature file versions could produce different scan speeds (though obviously, jumping from one second to 20 seconds, is pretty significant, and would suggest some problem somewhere in need of resolving regardless).

**Comment by cwolcott** [comment]
All the signatures files are installed from our GIT repository so all the servers are the same, but I will double check.  This morning I will perform the following:

- Reboot the development servers and test
- Upgrade to phpMussel 1.5 and test
- If we are still slow I will begin to debug the code.

We worked with you before on [Issue #148](https://github.com/phpMussel/phpMussel/issues/148).

**Comment by DanielRuf** [comment]
I would suggest trying to profile this with some solution like https://blackfire.io/

**Comment by DanielRuf** [comment]
Also is the hardware the same (HDD vs SSD and how much INode operations can be done at the same time).

**Comment by cwolcott** [comment]
Good news, but please don't close the issue unit I can confirm with we are fine on all development servers and production mid-next week.

My development server is now scanning the files without delay.  Here is what I tried:

- Reboot server (No effect)
- Upgrade to the latest signatures (No effect)
- Upgrade from 1.2.0 to 1.5.0 via composer (**SUCCESS**)

I don't see anything in the release notes that would have fixed us. The upgrade obviously gave us a clean phpmussel/phpmussel directory. So not sure if there was something that was impacting the scan (not likely, since it was only effecting certain pdf types).

**Note:** When trying to get v1.5.0 to execute for our test case (original post) I noticed/forgot that we had to change the config.ini token [general][cleanup] from true to false so that it could execute.  Otherwise $phpMussel was null.

I will have a chance later this week to test our other development servers to see which of the steps above finally allowed the scans to run without delay.

**Comment by Maikuolan** [comment]
Hm.. Interesting. Thanks for the update on the situation. :-)

No problem about not closing the issue. I can keep it open until not needed anymore.

Looking forward to hearing how it goes.

**Comment by Maikuolan** [comment]
@cwolcott How are things looking on your end at the moment?

**Comment by cwolcott** [comment]
I am so sorry about not updating this.  We are running just fine.  Please close the issue.  We are still running on v1.5, maybe we will look at upgrading to v1.9.0 by the end of the month.

**Comment by Maikuolan** [comment]
No problem; All good. :-) :+1:
