### ISSUE TITLE
No problems found on test files, clean install

### ISSUE THREAD

**Issue by Costegillio** [phpMussel/phpMussel#172]
Greetings!

I've got clean manual install on localhost. 
**All** signatures are Installed and activated via front-end panel. 
Default 'config.ini', the only two settings changed: 
1. check_archives = true
2. disable_frontend = false

Test files doen't detects (detects only by filetype blacklisted). I've tried to check text files on virusTotal and all of them are clean.

Also i've got "phpMussel – Verification failed" at config.php:

> actual 2a8283a6dbd7e91c68aedfd34f4b2a8d:8472
> expected a4bc008f53c6696b7acba5eadd4d8bc1:8429

A huge thanks!

### phpMussel version used (if known, please also include the exact commit hash).
v1.6.0

### PHP SAPI used (`<?php echo php_sapi_name(); ?>`).
apache2handler

### PHP version installed (`<?php echo phpversion(); ?>`).
7.1.12

### Operating system used (`<?php echo php_uname(); ?>`).
Windows NT ASUS 6.3 build 9600 (Windows 8.1 Professional Edition) i586

---
### Relevant scan_log entry (if applicable).
Thu, 04 Oct 2018 12:34:51 +0300 Started.
> Checking 'ascii_standard_testfile.txt' (FN: ce76ae7a; FD: 7b9bfed5):
-> No problems found.
Thu, 04 Oct 2018 12:34:51 +0300 Finished.
Thu, 04 Oct 2018 12:35:43 +0300 Started.
> Checking 'exe_standard_testfile.exe' (FN: bc2b0816):
-> Filetype blacklisted.
Thu, 04 Oct 2018 12:35:43 +0300 Finished.
Thu, 04 Oct 2018 12:37:06 +0300 Started.
> Checking 'ascii_standard_testfile.txt' (FN: ce76ae7a; FD: 7b9bfed5):
-> No problems found.
Thu, 04 Oct 2018 12:37:06 +0300 Finished.
Thu, 04 Oct 2018 12:39:43 +0300 Started.
> Checking 'coex_testfile.rtf' (FN: b0e404dc; FD: c44e0020):
-> Detected phpMussel-Testfile.CoEx!
Thu, 04 Oct 2018 12:39:43 +0300 Finished.
Thu, 04 Oct 2018 12:49:59 +0300 Started.
> Checking 'md5_testfile.txt' (FN: 26568969; FD: 4e8f9f87):
-> No problems found.
Thu, 04 Oct 2018 12:49:59 +0300 Finished.
Thu, 04 Oct 2018 12:52:57 +0300 Started.
> Checking 'exe_standard_testfile.exe' (FN: bc2b0816):
-> Filetype blacklisted.
Thu, 04 Oct 2018 12:52:57 +0300 Finished.

**Comment by Maikuolan** [comment]
Thanks for the report. :+1:

Latest commit should fix the verification error. Still investigating the other problem currently.

**Comment by Costegillio** [comment]
Caleb, thanks for fast response! I've tested and commented your commit.

**Comment by Costegillio** [comment]
Well, after switching my php version from '7.1.12' to '7.0.26' everything detects just fine.

Is there any way i can help you with log-files or something?

**Comment by Maikuolan** [comment]
> Caleb, thanks for fast response! I've tested and commented your commit.

Great! And thanks. :-)

> Well, after switching my php version from '7.1.12' to '7.0.26' everything detects just fine.
>
> Is there any way i can help you with log-files or something?

Glad that it seems to be working now. :-)

Though the method used to get there (or, more specifically, the fact that it worked) seems a little unusual to me, in that I wouldn't have expected there to really be any significant differences between running phpMussel on PHP `7.0.26` versus PHP `7.1.12`. I'll probably need to do some more research at some point I think, to try to understand this a little better.

> Is there any way i can help you with log-files or something?

I wouldn't worry it for the moment. If the problem has been solved, that's the main thing, I guess. I'm going to do some more research though to try to understand exactly why this worked, why the problem existed in the first place and so on. I'll let you know what turns up.
