### ISSUE TITLE
Gets logged out from frontend

### ISSUE THREAD

**Issue by basilky** [phpMussel/phpMussel#174]
phpMussel v1.6.0
php v7.2
Ubuntu 18.04

Just installed phpmussel using composer and enabled front end in config.ini. I was able to successfully login by default username and password.But after that if click on any links like Accounts,Cache Data,Configuration,File Manager etc, I'm getting logged out of front end. I was used version 1.5 of phpmussel and this issue was not there.

**Comment by Maikuolan** [comment]
Under `<phpMussel-root>/vault/fe_assets/`, there should be a `frontend.dat` file.

On my local dev copy, for example, the file looks like this (any real usernames and hashes in below example starred out, of course):

```
USERS
-----
YWRtaW4=,$2y$10$*****************************************************,1
bWF***********************==,$2y$10$*****************************************************,1

SESSIONS
--------
YWRtaW4=,$2y$10$*****************************************************,1540107759

CACHE
-----
```

Can you confirm:
1. That this file actually exists on your copy.
2. If it doesn't exist, what's the current permissions (CHMOD) for `<phpMussel-root>/vault/` (and thus also `<phpMussel-root>/vault/fe_assets/`)?
3. If it does exist, after trying to log into the front-end, can you open that file, and confirm whether anything appears under the "SESSIONS" heading?

Cheers.

**Comment by basilky** [comment]
Solved.Thanks for the reply.
The issue was because when I installed phpmussel using composer, all the generated files had owner and group as my username and not www-data.I recursively changed ownership and group to www-data, and the issue is gone.It was better if this was indicated in the documentation.

**Comment by Maikuolan** [comment]
No worries, and you're welcome. Glad to hear that the problem has been solved. :-)
