### ISSUE TITLE
Update packagist hook

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#186]
@Maikuolan you might have to logout and login again at packagist to update their hook.

> This package is using the legacy GitHub service and will stop being auto-updated in early 2019. Please set up the new GitHub Hook for Packagist so that it keeps working in the future.

See https://twitter.com/packagist/status/1037035587453235201?s=20

**Comment by Maikuolan** [comment]
Cheers. :+1: :-)

I'll get that sorted out now.

**Comment by Maikuolan** [comment]
And done.
