### ISSUE TITLE
Loader.php loads a white screen only

### ISSUE THREAD

**Issue by nocanvas** [phpMussel/phpMussel#189]
I uploaded everything, changed the config.ini and set disable_frontend=false. 

Attempted to access loader (domain.com/phpmussel/loader.php)
I get a white page. 

I've tried messing with permissions, can confirm vault is 755 -R

What am I doing wrong here.

## Server information.
Godaddy Shared Hosting 

##
### PHP version installed (`<?php echo phpversion(); ?>`).
5.6

**Comment by Maikuolan** [comment]
Definitely strange. Shouldn't normally need to do anything else, in order for the front-end to start working.

I looked over the codebase (in particular, the loader), to see whether I could find any possible causes for this. Can't see anything immediately there though.

Do you know whether there are any redirects happening at the server level, before PHP has a chance to see the request? If there are, that could possibly trick phpMussel into thinking that the request isn't an attempt to access the loader directly, therefore preventing the front-end from loading.

Also, could you try creating a new PHP file, somewhere on your server, containing this:
```PHP
<?php
echo 'Value for $_SERVER['SCRIPT_FILENAME']: ' . $_SERVER['SCRIPT_FILENAME'] . "<br />\n";
echo 'Value for __FILE__: ' . __FILE__ . "<br />\n";
```

..and let me know whether it shows the same value for both, or something different?

(No need to paste the exact values here. Issues posted here are publicly accessible, and those values could expose some of the directory structure for your server or website. Just want to know whether they're the same or different).

**Comment by DanielRuf** [comment]
Please check the error logs. It could be a memory_limit issue.

**Comment by nocanvas** [comment]
> ..and let me know whether it shows the same value for both, or something different?
> 

Thank you, the values are somewhat different, the script starts with var/chroot/home/content and the file starts with home/content

**Comment by nocanvas** [comment]
> Please check thd error logs. It could be a memory_limit issue.

My memory is set to 
memory_limit=64m

I've turned on error logs, but it takes a bit for them to be accessible, will report back

**Comment by nocanvas** [comment]
I see alot of this
[Mon Feb 25 05:02:38 2019] [xxx] [fcgid:warn] [client xxx:xxx] mod_fcgid: can't apply process slot for /web/cgi-bin/php-fcgi

**Comment by Maikuolan** [comment]
> Thank you, the values are somewhat different, the script starts with var/chroot/home/content and the file starts with home/content

Thanks for checking on this. :-)

I *suspect* that either Godaddy in general, or the particular Godaddy server in question, might be using symlinks to resolve user's hosting data (i.e., what you see on your account) to the actual location of that data on their server file system, thus causing `$_SERVER['SCRIPT_FILENAME']` and `__FILE__` to indicate different paths (and therefore preventing phpMussel from correctly identifying when a request is direct, which it currently does to determine whether to display the front-end).

If my suspicions are correct, then I think I have a good idea for how to fix the problem, but we should confirm first whether my suspicions are correct (the fix would, of course, be useless if my suspicions are wrong).

Like before, with the code that we tested earlier, could you create a new PHP file somewhere on your server, containing this:

```PHP
<?php
echo 'Value for realpath($_SERVER[\'SCRIPT_FILENAME\']): ' . realpath($_SERVER['SCRIPT_FILENAME']) . "<br />\n";
echo 'Value for __FILE__: ' . __FILE__ . "<br />\n";
```

..and let me know whether it shows the same value for both, or something different?

(The difference between the code that we tested earlier and this new code, is the absence/presence of `realpath()` -- I'm curious whether `realpath()` will produce any noticeable difference).

Cheers. :-)

**Comment by Maikuolan** [comment]
> mod_fcgid: can't apply process slot for /web/cgi-bin/php-fcgi

That error message is interesting. Basically, it indicates some kind of problem is occurring with PHP FastCGI. Not necessarily anything related to phpMussel, but could be worth asking Godaddy support about; It could indicate some kind of problem with the way that they've configured the server, or the way that PHP FastCGI has been set up (i.e., although not necessarily anything related to phpMussel, it could still nonetheless indicate that something is wrong somewhere that needs to be addressed).

**Comment by nocanvas** [comment]
Yes they were the same this time

Value for realpath($_SERVER["SCRIPT_FILENAME"]):
/home/content/xx/xxx/html/phpmussel/info.php
Value for __FILE__: /home/content/xx/xxx/html/phpmussel/info.php

**Comment by Maikuolan** [comment]
I committed a small change to the loader just now which should fix the problem. :-)

( fda090ed48a787e60d5f812c44ddbe36adf423e4 ).

The specific changed line:

```PHP
str_replace("\\", '/', strtolower($_SERVER['SCRIPT_FILENAME'])) === str_replace("\\", '/', strtolower(__FILE__))
```

Changed to:
```PHP
str_replace("\\", '/', strtolower(realpath($_SERVER['SCRIPT_FILENAME']))) === str_replace("\\", '/', strtolower(__FILE__))
```

When you get a chance, try either updating to the latest commit or manually amending your copy of the loader with the mentioned change, and let me know how it looks on your end afterwards. :-)

**Comment by Maikuolan** [comment]
I assume that the problem has been resolved. Marking accordingly and closing.
