### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by gunarecro** [phpMussel/phpMussel#194]
### Operating system used Windows NT INFO952 10.0 build 17134 (Windows 10) i586

---
## Issue
**Error:**
**Maximum execution time of 30 seconds exceeded in -> vault -> functions.php -> line 2532**

What is the maximum file size for the scan file?

Because Whenever I tried to upload more than a particular amount (MB) of file or image scan results is not coming more over it is coming as an internal server error. But  If i upload normally its working fine (without scanning). Do I need to change any configuration settings?

Please help me to rectify this issue.

Thanks
Guna

**Comment by DanielRuf** [comment]
> Maximum execution time of 30 seconds exceeded 

You have to increase it with `set_time_limit()` or `ini_set()`, see the `maximum_execution_time` in `phpinfo()`.

But it depends on your hosting provider and server settings if you can increase it and how much you can increase it.

This is not a phpMussel issue but a server / PHP config issue.

**Comment by gunarecro** [comment]
> > Maximum execution time of 30 seconds exceeded
> 
> You have to increase it with `set_time_limit()` or `ini_set()`, see the `maximum_execution_time` in `phpinfo()`.
> 
> But it depends on your hosting provider and server settings if you can increase it and how much you can increase it.
> 
> This is not a phpMussel issue but a server / PHP config issue.

Thank you
