### ISSUE TITLE
idea: plugin system

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#23]
Yes, this is just a very rough (and maybe not needed) idea, but this just came into my mind and it is better to think about this as soon as possible and ease the process to extend phpMussel and create an ecosystem fromt this later.

I had some ideas about additional features, but these should not be part of the phpMussel core.

Instead we should create a simple plugin system using hooks.

We could for example create this with call_user_func and an array like this:

```
call_user_func('before_scan',$GLOBALS['events']['before_scan']);
call_user_func('after_scan',$GLOBALS['events']['after_scan']);
...
```

and fill the array in plugin configuration files

```
$GLOBALS['events']['before_scan']['plugin_test']['dir']=__DIR__;
// or $GLOBALS['events']['before_scan']['plugin_test']['dir']=dirname(__FILE__);
$GLOBALS['events']['before_scan']['plugin_test']['file']="index.php";
$GLOBALS['events']['before_scan']['plugin_test']['function']="plugin_test_event";
```

and later process this for the individual events

So in the end, the logic is like this:

```
$GLOBALS['events'] = array();
//register plugin for event in the individual plugins which are auoloaded
$GLOBALS['events']['before_scan']['plugin_test']['dir']=__DIR__;
// or $GLOBALS['events']['before_scan']['plugin_test']['dir']=dirname(__FILE__);
$GLOBALS['events']['before_scan']['plugin_test']['file']="index.php";
$GLOBALS['events']['before_scan']['plugin_test']['function']="plugin_test_event";

//hook all registered plugins for event in phpMussel core
call_user_func('before_scan',$GLOBALS['events']['before_scan']);

//run registered plugins in phpMussel core
    // traverse all elements in $subscribers, each one is a plugin
    foreach ($subscribers as $key => $subscriber_values) {
        // $subscriber_values['file'];
        // $subscriber_values['function'];
        // $subscriber_values['dir'];
        // optionally include using $subscriber_values['dir'] and $subscriber_values['file'] if not autoloaded
        // execute function defined in $plugin['function'] with call_user_func or $plugin['function']()
        call_user_func($subscriber_values['function']);
    }
}
```

Just some ideas for possible plugins that I had or could make sense:
- [x] [mail report (send mail with all information about the malicious upload)](https://github.com/Maikuolan/phpMussel-plugin-notifications)
- [ ] vendor report (send malware binary zipped with the standard password to all vendors)
- [ ] statistics / analytics (prevented malware uploads)
- [ ] permanent block (create CIDR rules / IP rules for Deny from directives and save to .htaccess)
- [ ] dashboard (information about phpMussel like status)
- [ ] caching (use an existing caching software with own configuration)
- [x] [database (connect phpMussel to a database which it should use)](https://github.com/mtrefzer/plugin-log2mysql)
- [ ] log / log transform (use specific or own log format)
- [ ] poormanscron (bundle all cron tasks in one file which will be executed at a specific interval or can be executed with one single cron. Cache, update, ... and other tasks)
- [ ] manager / phpMussel host (central host with remote deployment feature and phpMussel client monitoring / status)
- [ ] image / file optimization (if specific files are uploaded, optimize them after phpMussel flags them as benign)
- [ ] RSS feed (hidden rss feed for admins where they get all phpMussel events as news, instead of mail report).
- [ ] ISC / DShield / Project Honeypot (directly block malicious IPs eg servers, Tor users, bots, ...)

Plugin boilerplate: https://github.com/phpMussel/plugin-boilerplate-v1

**Comment by Maikuolan** [comment]
I like the idea, and I definitely think this is something we should look into doing. :-)

I'm leaving the "Attention Required" label on this issue, because I haven't had enough time the past few days to write a reply that properly addresses everything you've suggested, and I want to do that; Hopefully tomorrow I'll get enough time to do so.

**Comment by Maikuolan** [comment]
Worth planning for; A system like this would also further allow others to develop for phpMussel without necessarily needing to worry about re-hooking to the core with each new core update and things like that; Could also provide a reliable way to allow for custom functionality that may require access to various parts of the core that without such a system would otherwise probably require a heavy degree of editing of the core itself, so, a plugin system like this, definitely, would make it easier for other developers to write things for phpMussel.

There a many ideas that in the past I've thought I'd like to see in phpMussel, but which haven't really been properly within the scope of phpMussel's purpose, and I do think that any -core- features should remain within the scope of phpMussel's purpose (to avoid scope-creep and to avoid anyone in the future questioning what phpMussel is actually intended for), but a plugin system like this would help, because it would allow us to try out some of these ideas without worrying about things like scope-creep.

It could also help end-users, too, because it would allow a greater level of scalability in regards to what they do and don't want (as in, if they want something that a plugin offers, they can use that plugin, or, if they're not interested, they can simply ignore it and not use it).

If you wanted to plan some things out for it, I think, that would fine. Quite a few other things to get done first before implementing this, of course, but, I think, eventually, this will be something to do.

**Comment by DanielRuf** [comment]
Right. The core should not be touched (which would break updates) and phpMussel can be modularized / extended with the plugin system in the future, which creates many new possibilities and addresses the different needs of more users.

The available hooks for plugins have to be accordingly planned and named

Definitely something needed for a bigger target group (different uses and needed custom features) and ecosystem.

I will plan some plugins in the future and prepare something and test it, when we have an implementation of a plugin system.

**Comment by Maikuolan** [comment]
I've been playing around with some ideas for this, and, by using `call_user_func()` as suggested, I think I've found a way to pass variables across scopes, without needing to change too much, and a way to hook plugins to various parts of the script without needing to change core code for plugins.

Testing locally, it seems to work, but, it's a little rudimentary at the moment, so, probably needs work.

I've uploaded a **[plugin boilerplate](https://github.com/Maikuolan/phpMussel-plugin-boilerplate)** (still alpha, until we can eventually decide how to standardise this), and I'll create a new branch soon to show what I've worked out.

**Comment by Maikuolan** [comment]
I think, too, we'll need to decide where to put some hooks into the core code.

I had some basic ideas, but, would like to know what you think.
- Before executing the core script.
- Before each scan.
- At the end of each scan, prior to caching results.
- After each scan.
- Before displaying the "Upload Denied" message/page.
- After executing the core script.

**Comment by DanielRuf** [comment]
> I've been playing around with some ideas for this, and, by using call_user_func() as suggested, I think I've found a way to pass variables across scopes, without needing to change too much, and a way to hook plugins to various parts of the script without needing to change core code for plugins.
> 
> Testing locally, it seems to work, but, it's a little rudimentary at the moment, so, probably needs work.
> 
> I've uploaded a plugin boilerplate (still alpha, until we can eventually decide how to standardise this), and I'll create a new branch soon to show what I've worked out.

Great, I will take a look at it and see if I can help with anything.

> Before executing the core script.
> Before each scan.
> At the end of each scan, prior to caching results.
> After each scan.
> Before displaying the "Upload Denied" message/page.
> After executing the core script.

I created a workflow of phpMussel on paper and so far I found only these 6 hooks.

**Comment by Maikuolan** [comment]
I added some more hooks just now.

Current hooks:
- <strike>"before_phpmussel"</strike>
- "before_scan"
- "during_scan"
- "after_vt"
- "after_scan"
- <strike>"before_scan_mail"</strike>
- <strike>"after_scan_mail"</strike>
- "before_html_out"
- <strike>"after_phpmussel"</strike>

**Comment by Maikuolan** [comment]
Some information regarding:

> - vendor report (send malware binary zipped with the standard password to all vendors)

_Source: http://www.techsupportalert.com/content/how-report-malware-or-false-positives-multiple-antivirus-vendors.htm_

> **2. Easily Submit Malware To All Vendors**
> One of the main purposes of this article is to make it as easy as possible for anyone who comes across malware to submit it to all security vendors in as few steps as possible. Also, don't worry about duplicate submissions. This has been taken care of for this list.
> 
> You can submit the password protected **zip file** by clicking on **[this link](mailto:v3sos@ahnlab.com;virus@avast.com;virus@avira.com;virus_submission@bitdefender.com;samples@bluepointsecurity.com;malwaresubmit@avlab.comodo.com;vms@drweb.com;malware@emcosoftware.com;submit@emsisoft.com;virus@esafe.com;samples@escanav.com;submitvirus@fortinet.com;research@spy-emergency.com;viruslab@f-prot.com;labs@fsb-antivirus.com;vsamples@f-secure.com;samples@ikarus.at;submit@samples.immunet.com;newvirus@kaspersky.com;support@jiangmin.com;research@lavasoft.com;virus_research@avertlabs.com;virus@micropoint.com.cn;avsubmit@submit.microsoft.com;virus@nanoav.ru;samples@eset.com;support@noralabs.com;support@norman.com;virus_info@inca.co.kr;virus@pandasecurity.com;psafe@psafe.com;kefu@360.cn;support@rubus.co.in;newvirus@s-cop.com;samples@sophos.com;detections@spybot.info;vlab@srnmicro.com;avsubmit@symantec.com;virus@hacksoft.com.pe;virus@thirtyseven4.com;virus@ca.com;submit@trojanhunter.com;support@simplysup.com;virus@filseclab.com;malware-cruncher@sunbelt-software.com;viruslab@hauri.co.kr;newvirus@anti-virus.by;virus@zillya.com;huangruimin@kingsoft.com;pomoc@mks.com.pl;support@aegislab.com;viruslab@quickheal.com;trojans@agnitum.com;bav@baidu.com;bkav@bkav.com.vn;huangruimin@kingsoft.com;samples@mysecuritywin.com)**. (Attach zip file after email client opens and then click send)-Webmail users should right click on it and choose to save the email addresses. Then paste them in the contact line of your email.
> 
> You can submit the password protected **7z file** by clicking on **[this link](mailto:support.is@cmclab.net;samples@digital-defender.com;sample@preventon.com;support-tech@returnil.com;malwaresample@herdprotect.com;info@chicalogic.com;submit@antiy.com;virus@arcabit.com)**. (Attach 7z file after email client opens and then click send)-Webmail users should right click on it and choose to save the email addresses. Then paste them in the contact line of your email.
> 
> If the email is not delivered correctly please see my comments in section A1 to make sure that you are not using one of the email services which do not work with this list.

..And so, based on this information, if the ability to compress binaries as ZIP and 7z archives was integrated to phpMussel, and if phpMussel was able to send emails natively (and from an accepted mail server), in theory, those binaries could be sent, immediately, to a wide-range of vendors, by using those addresses.

Definitely useful to know. :-)

I understand that Virus Total shares its submissions with various vendors, too, and I hope to eventually be able to do that with phpMussel as part of the included Virus Total integration.

**Comment by DanielRuf** [comment]
This would be great but as far as I know encryption of zip files is not directly possible using PHP but system and exec function calls.

Theoretically it should be possible using the zip format specification were PKWARE, AES, the structure of the headers and so on are described.

**Comment by Maikuolan** [comment]
_Temporarily removing the Work-In-Progress tag due to the possibility of the current plugin system changing for v1.0.0, for in the event of adopting the OOP/classful implementation or the fat-free closure-based implementation of phpMussel._

**Comment by Maikuolan** [comment]
_Linked **mtrefzer/plugin-log2mysql** to the entry for "database (connect phpMussel to a database which it should use)"._

**Comment by Maikuolan** [comment]
Completely overhauling the entire plugin system for v3. None of the currently existing plugins will be compatible with v3, but I'll work on replacing them all with v3-specific alternatives anyway. I'll be completely dropping the dedicated plugin hooks system in favour of using the events system, and it'll be possible to integrate plugins directly via Composer. Still working on it (not functional yet), but I'll reply again when it's ready. :-)

**Comment by Maikuolan** [comment]
> but I'll reply again when it's ready. :-)

Done. :-)

Also, new boilerplate for v3: https://github.com/phpMussel/plugin-boilerplates/tree/master/boilerplate-v3

Haven't tagged/marked phpMussel v3 as production ready yet, but will probably get there soon, I think.

**Comment by Maikuolan** [comment]
Thinking I might go ahead and close this now. Creating plugins ourselves is quite a lot of work, and even if we think something is a good idea, there's no guarantee that other users will think it is a good idea, or that they will use it. Probably easier and less time-consuming to not worry too much about it, just focus instead on the core and other orbiting repositories/components, and if users express interests towards implementing specific ideas for plugins, or if they seek help about how to do it, we can help them out. If plugins appear which seem cool, we can then add them to the list of known plugins. But, realistically, I'm not sure I want to spend too much time on developing them myself anymore. If I find some time in the future though, I may still try to develop a few; if that happens, I can just create a notice or something about them, or add them directly to the list.
