### ISSUE TITLE
solution: ERR_CONNECTION_RESET when uploading on Windows (Apache / XAMPP)

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#24]
When uploading some files like html_standard_testfile.html on a Windows machine where XAMPP (Apache) is running, the site loads very long and then the connection is reset.

This is a known PHP problem in Apache.
You will see this in the error.log file of Apache:

```
[Thu Jun 25 23:07:16.413547 2015] [mpm_winnt:notice] [pid 7744:tid 388] AH00428: Parent: child process 7332 exited with status 3221225725 -- Restarting.
```

Try adding this to the end of httpd.conf (you should find this file at C:/xampp/apache/conf/httpd.conf):

```
<IfModule mpm_winnt_module>
   ThreadStackSize 8388608
</IfModule>
```

References: 
http://stackoverflow.com/questions/5058845/how-do-i-increase-the-stack-size-for-apache-running-under-windows-7
http://stackoverflow.com/a/7597506/753676
http://www.codexpedia.com/apache-server/parent-child-process-exited-with-status-3221225725-restarting-on-xamp-apache/

The default stack size for Linux is 8MB, for Windows it is 1MB.
https://bugs.php.net/bug.php?id=60231

```
 [2013-05-27 15:11 UTC] frank dot ralf at comm-press dot de
The solution is increasing the ThreadStackSize from 1 MB (default under Windows) to 8 MB (default under Linux), see http://stackoverflow.com/questions/5058845/how-do-i-increase-the-stack-size-for-apache-running-under-windows-7 for details.
```

http://stackoverflow.com/questions/5058845/how-do-i-increase-the-stack-size-for-apache-running-under-windows-7

So actually this is not a bug (but maybe a misconfiguration of the default Apache under Windows).

**Comment by Maikuolan** [comment]
Good to know. o_0

Most of my local testing is done using Nginx, so, this is something I wouldn't have been likely to have ever found. Thanks for testing and finding it.

**Comment by DanielRuf** [comment]
I have updated the issue with some more details, so this issue often also affects other webapplications running on Apache under Windows.

We should keep this issue open to point users here, if they encounter the same issue.

You are welcome. I also did not know that there is this difference between Linux and Windows regarding the default stack size (for Apache) so testing is very crucial to identify such issues and document them in the documentation (troubleshooting issues).

**Comment by Maikuolan** [comment]
> We should keep this issue open to point users here, if they encounter the same issue.

Agreed.

Definitely a very interesting thing to find out about (the different stack sizes)!

**Comment by Maikuolan** [comment]
We can still point users here if this issue is encountered again in the future, regardless. Closing the issue for now in order to try to clean up the issues list a bit (the list of open issues is getting a bit large), but we can reopen the issue at any time if need be, to continue the discussion, facilitate further questions, follow-ups, etc.
