### ISSUE TITLE
suggestion: block password protected / encrypted archives

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#26]
We could check if an archive has a password / is encrypted (and block if set in configuration) as a custom password would change the CRC and encrypted files can not be checked / scanned. They would be flagged as benign but are higly malicious.

RAR: 
0x04 - file encrypted with password
0x0080 - Block headers are encrypted
http://forensicswiki.org/wiki/RAR

ZIP: check first bit of the seventh byte
http://stackoverflow.com/questions/12081839/how-to-check-if-encrypted-zip-archive-in-php
https://github.com/CuteNews/cutenews-2.0/blob/master/core/zip.class.php

https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

```
4.4.4 general purpose bit flag: (2 bytes)
        Bit 0: If set, indicates that the file is encrypted.
```

Some version info can also be used (not all versions listed, 6.3 can also be unencrypted) to check if the file is password protected / encrypted

```
4.4.3 version needed to extract (2 bytes)
        2.0 - File is encrypted using traditional PKWARE encryption
        5.0 - File is encrypted using DES
        5.0 - File is encrypted using 3DES
        5.0 - File is encrypted using original RC2 encryption
        5.0 - File is encrypted using RC4 encryption
        5.1 - File is encrypted using AES encryption
        5.1 - File is encrypted using corrected RC2 encryption**
        5.2 - File is encrypted using corrected RC2-64 encryption**
        6.1 - File is encrypted using non-OAEP key wrapping
        6.2 - Central directory encryption
        6.3 - File is encrypted using Blowfish
        6.3 - File is encrypted using Twofish
```

In reference to https://github.com/Maikuolan/phpMussel/issues/2

This ticket was created to track it for future commits.

**Comment by Maikuolan** [comment]
I've written up something simple relying on the first-bit-seventh-byte flag to check if ZIPs are encrypted, it seems to be working and it seems to be stable, but haven't yet done anything for RARs or anything else, and work still needs to be extended much further (detection for other formats, detecting encryption flags within the headers of individual files contained within archives, and eventually, maybe, something to attempt to decrypt files using the detected encryption method when an encryption key/password is available for use).

My next commit will contain this partial implementation and will reference this issue.

**Comment by DanielRuf** [comment]
Great. I will test this then with some files and see what I can commit.

I have to check if and how this can be done for other archive formats, I will research on this.

I am currently working on the themes / designs for the template.html file, I will send a first draft (or more) next week or so.

**Comment by Maikuolan** [comment]
Awesome, sounds good. :-)

**Comment by DanielRuf** [comment]
So far the password protected zip files are properly detected and blocked by phpMussel.

I have to do more tests with different encryption methods but so far it looks very good.

Todo: prepare zip files with different encryption methods, maybe there are some tools for this.

**Comment by Maikuolan** [comment]
Closing as implemented.
