### ISSUE TITLE
Wish list: Translations audit.

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#3]
I've done a handful of multilingual translations for phpMussel, though, unfortunately, the only language that I actually speak or know fluently is English, and so, although the translations that I've done have been done to the best of my abilities and have been done accurately to the best of my knowledge, it wouldn't surprise me in the slightest if there were, in fact, numerous errors in my translations.

Credit for the German translations goes to BlueEyed Zebra, for whose assistance I am very grateful for (I haven't done any of the German translations myself at all). I had assistance with getting the Indonesian translations done in the early days, but have since entirely taken over that myself, and all the others I've done entirely by myself.

For any currently supported languages (other than English, German and Indonesian, at this time, includes Spanish, French, Italian and Portuguese; Dutch is also partially supported, although I haven't yet gotten around to finishing complete support for it), if any native speakers thereof could give them a quick look over and confirm if there are any errors or not (and if there are any errors, point them out to me or try to correct them), that would be greatly appreciated, and for any languages not currently supported, if there are any native speakers thereof that would be willing to work towards making their language supported, that would also be very welcomed.

Also as a quick question to anyone that might know: Regarding non-ASCII languages (such as Chinese, Japanese, Russian, Korean, Greek, etcetera); Any idea how that could be made to work with CLI functionality? Easy enough to get the right encoding for the browser-side of things most of the time, but I don't have much experience dealing with it when it comes to CLI.

**Comment by DanielRuf** [comment]
I would try it with `mbstring.internal_encoding = UTF-8`

http://www.saturngod.net/articles/php-cli-with-unicode/

The used font (TTF, not a raster font) should also support the language.

**Comment by Maikuolan** [comment]
Nice find. I'll give that a try and report my results back here. :-)

**Comment by Maikuolan** [comment]
Didn't seem to quite do the trick in the way that I'd hoped. :-/

Been googling a bit more on the subject, and the only two sure-fire ways I've been able to find to do it would be to (1) switch the actual code page used by CMD (except that, unfortunately, I don't think it's possible to do that in a non-persistent way) or (2) have those using phpMussel in CLI mode change their actual Windows region/locale and language settings to conform to what is required for their choice of language in phpMussel, and neither of those two ways are particularly appealing; It seems, from what I've been reading, that CMD just isn't wholly compatible with UTF-8 in the way that I'd like it to be, in order to properly support CLI functionality in a way that would allow phpMussel to correctly display non-ANSI/non-ASCII characters (it's rather frustrating that Windows doesn't seem to play nicely with UTF-8 in certain ways like this).

That said though, I'll keep the `mbstring.internal_emcoding = UTF-8` modification that I've put in (commit not yet sent in; will do that very shortly), because I've found that it's been very useful in a few other ways; It's allowed phpMussel to display UTF-8 characters correctly in the browser without any issues (that I'm aware of, at least), and without the need for HTML entitisation of UTF-8 characters (which is what I'd been doing previously in order to display them correctly), and converting characters in the `lang.inc` from ANSI/ASCII and HTML entities to UTF-8 characters has resulted in a decrease in filesize for that file and has also resulted in that file being somewhat more intelligible/readable.

Anyhow, I'll send in a new commit shortly.

**Comment by DanielRuf** [comment]
That is right. Unfortunately Windows always used another special encoding for the commandline and using Windows encoding per default is not the best solution.

There are always more problems with Windows than Linux. Most users will run phpMussel on Linux and use a shell which should support UTF-8 / unicode characters if properly configured. At least the client application has to be set to UTF-8 / unicode explicitely.

Did you use `mbstring.internal_encoding` with an n? Because there was a small typo by me and I have written emcoding instead of encoding.

Also `default_charset = "utf-8"` is sometimes helpful in HTML code and so on.

https://www.google.com/search?q=chcp+65001

http://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how
http://stackoverflow.com/questions/1650369/php-utf-8-to-windows-command-line-encoding

So maybe a small batch file for windows makes sense, which will open the commandline, switch to the right codepage and so on. But I would say that this is not high priority and not necessary as people who run PHP on Windows machines will know this and are just a small percentage of all users running PHP on the CLI.

What do you think? At least forcing UTF-8 / unicode output for phpMussel makes sense.
The cleint has to support it, which should not be our problem and can not be fixed from the application side.

**Comment by Maikuolan** [comment]
Yeah, I agree; Forcing UTF-8 output for phpMussel does make sense, so, I think we should do that, and, if the client doesn't support it, then that isn't our problem, because trying to fix issues that are external to phpMussel is outside its scope anyhow.

Definitely not a high priority, but interesting food for thought nonetheless.

**Comment by DanielRuf** [comment]
I will ask some friends and people with who I have worked on several translation/localization projects to help with the translations.

**Comment by Maikuolan** [comment]
Greatly appreciated! :-)

**Comment by Maikuolan** [comment]
Found somebody to audit/update the Italian language data and documentation (thanks to @[Zangune](http://sourceforge.net/u/zangune/)).

:-)

_Reference - https://sourceforge.net/p/forge/helpwanted/translation/thread/28aff8dc/_

**Comment by DanielRuf** [comment]
Great =)

**Comment by DanielRuf** [comment]
Adding a reminder for me to prepare the translated strings for this commit: https://github.com/Maikuolan/phpMussel/commit/543fb3fd17488dbbd1e2396fb480025b9c4b24f9

**Comment by Maikuolan** [comment]
I found someone (they're not on GitHub; found through an alternate source, so, I'm not sure how I should link to them) willing to try to translate the documentation and language data to Arabic (definitely a worthwhile translation to have considering the number of native Arabic speaking internet users there are, but, not a language I'd enjoy attempting to do myself; I only know maybe four or five words in the language and I find it very difficult to distinguish between some of the characters, especially being a cursive script; the person offering to translate it for us, though, is a native speaker); She's told me it should take about a week to do. If all goes well, hopefully, in a week or so, we should have that done. :-)

**Comment by DanielRuf** [comment]
This is really great because Arabic is missing at the moment and many people write and speak Arabic.

Awesome, looking forward to the new translations. =)

Which platform(s) do you use to find new translators?

**Comment by Maikuolan** [comment]
I've tried a few different platforms; Most, I didn't have much (or any) success with.

This Arabic translator I found, I found using [Upwork](https://www.upwork.com). It's a platform for freelancers to find work and for employers to find freelancers. I'll need to pay some money for this translation, but, that's okay; The person I found has very good, very affordable rates, and has a strong record for work done in the past, so, I'm not concerned about it.

**Comment by DanielRuf** [comment]
Ah ok, I also found Upwork but was not active there for now.

**Comment by Maikuolan** [comment]
I've registered phpMussel as a open-source project with POEditor ([linked here](https://poeditor.com/projects/view?id=43787)).

Although the language files for phpMussel are normal PHP files and phpMussel doesn't use PO/MO/POT files, and although it's more efficient and convenient in my opinion to just work directly with the PHP files rather than mess around with an unnecessary third-party format, the reason I thought I should register there, is because, unlike many other PO/MO/POT translation managers available, POEditor seems to be able to directly upload and download PO files (meaning that users aren't forced to edit through some arbitrary system they provide), but additionally, they do provide an in-browser editing feature that actually seems to work pretty well, and so far, hasn't caused any problems for me while testing it (I tested a few other translation managers in the past, and most of them, I felt, were either too difficult to learn [or, I could learn them, but, they would be too difficult for non-tech-savvy people to learn to use, like those that might be interested in helping but who don't want to work with PHP] to use and/or had too many flaws, bugs, would time-out during editing and etc).

Registering there should mean that anybody that might be interesting in helping with translations, doesn't necessarily need to know anything about PHP (a few times in the past, I found some people that seemed interested in helping to translate, until I mentioned PHP files, and then they got scared off the idea of helping, it suddenly sounded too hard and complex for them to do, and that sort of thing), and additionally, anybody that prefers working with the PO format, can do that, for helping.

Any work done here will still need to be manually converted back into PHP files in order to comply with the system that phpMussel is currently using for translations (the `lang.%%.php` files) and to therefore be usable by phpMussel, but, this is something I don't mind doing, if it encourages people to help with translations. Anybody that is able to work directly with the PHP files should probably still do that, though.

I'm going to try to start making PO file versions of all the currently completed translations, to upload them to POEditor, so that it can be populated with some data; I'll commit the PO files, too, to the extras repository, when they're all done, so that they can be downloaded from there, for anyone that wants to work with PO files but doesn't want to get them individually from POEditor.

**Comment by DanielRuf** [comment]
Awesome, I already worked with POEdit, other platforms and tools for Gettext in the past. Makes translation much easier and we ca easily invite more people to help with the translation.

PO files are very neat and are also supported by PHP (I think with the gettext functions).

Let me know when this is done and I will share it, to get more translators onboard.
Do we have the free open source localization plan there (unlimited strings)?

Gettext is also available without the PHP module: https://github.com/oscarotero/Gettext

I do not know how many have the gettext module compiled into their PHP version but at least my hosting provider has it compiled into PHP for all versions. (PS: They also have now PHP 7 for me, maybe I move to a newer server with PHP 7 next year or so).

**Comment by Maikuolan** [comment]
Cool. I haven't looked much into gettext; Something to add to my to-do list, for things to research, :-)

Yep, we've got the free open source plan, so, unlimited strings.

And done; PO files have been created, [committed to the extras repository](https://github.com/Maikuolan/phpMussel-extras/tree/master/PO) and also uploaded to POEditor.com (I've marked most of them as fuzzy, to be safe).

**Comment by Maikuolan** [comment]
Sporadically too busy at work tonight during the night shift to do any serious work, but quiet enough that I've got enough spare time to do some small things here and there, so, purely for the sake of interest, to see where we're at with i18n, relative to the (top 10) wider internet linguistic demographics as per described by the Wikipedia article for "[Languages used on the Internet](https://en.wikipedia.org/wiki/Languages_used_on_the_Internet)" (although I don't know where this information comes from or how it's calculated), as of the current date (the page mentions this information was as of 18 March 2015):

Via "Internet users by language":

| _Rank_ | _Language_ | _Internet users_ | _%_ | _/_docs/ READMEs_ | _/lang/ strings_ |
| --- | --- | --- | --- | --- | --- |
| 1 | English | 800,625,314 | 28.6% | Completed/Good | Completed/Good |
| 2 | Chinese | 649,375,491 | 23.2% | Completed/Good | Completed/Fuzzy/Confident |
| 3 | Spanish | 222,406,379 | 7.9% | Completed/Fuzzy/Confident | Completed/Fuzzy/Confident |
| 4 | Arabic | 135,610,819 | 4.8% | Work In Progress | Work In Progress |
| 5 | Portuguese | 121,779,703 | 4.3% | Completed/Fuzzy/Confident | Completed/Fuzzy/Confident |
| 6 | Japanese | 109,626,672 | 3.9% | Work In Progress | Completed/Good |
| 7 | Russian | 100,700,000 | 3% | Completed/Good | Completed/Good |
| 8 | German | 81,139,942 | 2.9% | Completed/Good | Completed/Good |
| 9 | French | 78,891,813 | 2.8% | Completed/Fuzzy/Confident | Completed/Fuzzy/Confident |
| 10 | Malay/Indonesian | 75,459,025 | 2% | Completed/Good | Completed/Good |

Via "Content languages for websites":

| _Rank_ | _Language_ | _%_ | _/_docs/ READMEs_ | _/lang/ strings_ |
| --- | --- | --- | --- | --- |
| 1 | English | 55.5% | Completed/Good | Completed/Good |
| 2 | Russian | 5.9% | Completed/Good | Completed/Good |
| 3 | German | 5.8% | Completed/Good | Completed/Good |
| 4 | Japanese | 5.0% | Work In Progress | Completed/Good |
| 5 | Spanish | 4.6% | Completed/Fuzzy/Confident | Completed/Fuzzy/Confident |
| 6 | French | 4.0% | Completed/Fuzzy/Confident | Completed/Fuzzy/Confident |
| 7 | Chinese | 2.8% | Completed/Good | Completed/Fuzzy/Confident |
| 8 | Portuguese | 2.5% | Completed/Fuzzy/Confident | Completed/Fuzzy/Confident |
| 9 | Italian | 1.9% | Completed/Fuzzy/Confident | Completed/Good |
| 10 | Polish | 1.7% | Non-existent | Non-existent |

**Comment by Maikuolan** [comment]
Got someone to begin work on the Japanese translations. The same person, actually, that did the translations for my CMS some years back (I was happy with the job they did), so, I'm really happy about this. :+1: 

Should have an updated `lang.%%.inc` file ready soon and possibly a translated README in the near future.

**Comment by DanielRuf** [comment]
Awesome =)

Should ask one of my spanish contacts for a spanish translation (audit)?

**Comment by Maikuolan** [comment]
Definitely. Currently, the Spanish translations (both the internal language data and the readme) have been done by myself, basically, using a combination of Google Translate, my limited knowledge of the language (I know a -small- amount; I could introduce myself, but, beyond that, I would likely very quickly fail in any conversation), and manually eyeing over everything very carefully, to look for any very obvious errors and to make adjustments based on what "feels" correct. I'm more confident with Spanish than I am with say.. Chinese, for example.. But that said.. I'm still certain there are going to be a ton of errors and mistakes that I've missed. So, yeah; An audit would be warmly welcomed. :-P

(Same case, too, for most of the translations I've done myself; I feel they're probably "good enough" to be mostly understood, but, probably still very erroneous).

**Comment by ghost** [comment]
Hi! I would audit your spanish translation. Are you interested in?

Fernando

**Comment by DanielRuf** [comment]
@kfern-github you can do so at https://poeditor.com/projects/view?id=43787 or you fork the project / download the file from the master branch and update it.

**Comment by ghost** [comment]
Ok. I prefer poeditor. I'm adding some comments in translations. Is it ok?

**Comment by DanielRuf** [comment]
Great, thanks. Comments in the poeditor project with their comments feature? Should be ok. @Maikuolan?

**Comment by Maikuolan** [comment]
Yep, should be okay, and thanks for the help! :+1: 

Coincidentally.. Another person also offered to help with the Spanish translations audit, too, a few days ago (this other person via SourceForge), but, they're also using POEditor to do it, so, I don't think having two people would conflict or create any problems (editing directly from GitHub could be problematic with multiple people, due to possible merge conflicts and work duplication, but, these problems shouldn't exist with POEditor, because of how POEditor does editing line-by-line {so, one entry at a time, and simultaneous edits between multiple users is possible}, it allows comments, so, people can write what has and hasn't been done, can write about any possible problems they've found and etc, can mark entries as fuzzy {if something is incomplete or if we're unsure about it} and/or as proofread {when something is good and requires no change}, and it also shows who's connected at any given time and tracks a history of changes, so, with POEditor, it just means it'll probably be completed more quickly, so, no problems). I think, so far, this other person has audited roughly four or five or so sentences that they've checked through, but hasn't done the rest yet, so, there's still plenty to do.

In any case, the help is greatly appreciated. :-)

**Comment by Maikuolan** [comment]
Closing this issue. Pull requests can be made by anyone at any time when problems are found, anyhow; Chances are that there'll be things to correct into the future anyhow, as new features are implemented, parts of the script changed, changes are made to the documentation accordingly and such things.
