### ISSUE TITLE
Documentation streamlining/clarity

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#37]
This issue created for the purpose of tracking changes made to the documentation in relation to streamlining and improving clarity.

---

_In reference to the discussion [here](https://github.com/Maikuolan/phpMussel/commit/47a51a2fc3c4ef482a767eb123654e2263676ceb)._

_(DR)_

> _I am a bit confused._
> _Shouldn't be the two options before the texts like in the *.md file? ;-)_

_(CM)_

> _Yeah, I think you're right. I started doing it one way, and then switched to the other way. We can fix the *.txt files, so that they're like the *.md files; That way, everything will be more consistent. I hadn't thought much on this before, but it could potentially create confusion, and the documentation, considering what it's for, shouldn't be structured in a way that could create confusion._

_(DR)_

> _Right, you can create an issue for this and we will look at this in the future. I will analyse then the files and see where changes might be needed to prevent confusion._

I will begin working on the aforementioned issue tonight and will reference this issue when finished.

**Comment by DanielRuf** [comment]
Is the aforementioned issue fixed?
https://github.com/Maikuolan/phpMussel/commit/6a59cc9aaeb2ce0f37cb682a355af40d793aa910

**Comment by Maikuolan** [comment]
Yeah, I think it looks okay now. Should I keep this issue open for future changes, or close it?

**Comment by DanielRuf** [comment]
Keep it open for a while. If we have nothing to add and there will be no changes related to this issue, close it.

**Comment by Maikuolan** [comment]
Sounds good. :-)
