### ISSUE TITLE
PHP7 Compatibility

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#38]
In reference to this: https://github.com/php/php-src/blob/php-7.0.0alpha2/UPGRADING

Having read through that document, I can't see any potential problems for phpMussel (I don't think it's relying on anything that's been changed, depreciated, etc), but also, I haven't tested phpMussel on PHP7 to confirm whether there'll be any problems or not.

At some point, when there's time, phpMussel should be tested on PHP7 to confirm whether any changes will be required in order for it to be compatible.

**Comment by DanielRuf** [comment]
Right. I think I will install a new webserver on my computer which supports switching to PHP 7

Link to the latest snapshots of PHP7 for Windows:
http://windows.php.net/downloads/snaps/master/

Link to PHP 7 Alpha 2
http://windows.php.net/downloads/qa/

If `php7apache2_4.dll` is missing, read this bugreport:
https://bugs.php.net/bug.php?id=69801
I think I will also do some benchmarking with ApacheBench (ab).

Trying to get PHP 7 working with WAMP using this article: http://www.eboodevelopment.com/run-php7-0-0alpha1-on-wamp-server/

Finally I got it working with a version from http://sourceforge.net/projects/miniserver/ using the PHP 7 module http://sourceforge.net/projects/miniserver/files/Uniform%20Server%20ZeroXI/ZeroXImodules/

**Comment by Maikuolan** [comment]
Cool. :-)

**Comment by DanielRuf** [comment]
So far phpMussel works with PHP 7 but I have to do more tests with a newer build (there will be a first release of PHP 7 available this week afaik).

**Comment by Maikuolan** [comment]
Downloaded [RC8](http://php.net/archive/2015.php#id2015-11-26-1) earlier today and did some simple scanning in CLI and did the standard testfiles upload testing, and didn't encounter any problems. So far, so good.

**Comment by DanielRuf** [comment]
Very good. RC8 should be the last RC build before the final release. Do you think we need more testing or can we say it works with PHP7 and close the issue?

**Comment by Maikuolan** [comment]
Although usually, waiting to test against the actual, final release, would be recommended, because the PHP team is planning to only make bug fixes between now and the final release (to my understanding), if any new bugs are discovered (so, no new features or backwards incompatible changes to be made), I think it should be safe to close the issue and say that phpMussel is compatible with PHP7 (if the only differences between RC8 and the final release of PHP7 are to be bug fixes, and we can't find any bug or problems with running phpMussel with PHP7, then, it should work correctly with the final release, too).

I'll close this issue now. :-)

**Comment by Maikuolan** [comment]
New patch release for PHP available (PHP 7.0.2); Tested just now against the current master codebase; No problems found.
