### ISSUE TITLE
Wish list: Certificate parsing.

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#4]
ClamAV is able to read and parse the certificates of PE files and then check those certificates against its database to help ascertain whether or not a particular PE file should be trusted.

phpMussel hasn't yet been coded to do this, and thus, at this time, can't make use of that part of the ClamAV signatures database.

Not a high priority, but, something that nonetheless would be cool to amend.

**Comment by DanielRuf** [comment]
For reference: https://github.com/Maikuolan/phpMussel/issues/5#issuecomment-105014586

**Comment by DanielRuf** [comment]
Some useful article by Lenny Zeltser
https://isc.sans.edu/diary/Extracting+Digital+Signatures+from+Signed+Malware/15779

Pyew
https://github.com/joxeankoret/pyew
https://github.com/joxeankoret/pyew/tree/wiki

Disitool (uses pefile)
http://blog.didierstevens.com/programs/disitool/
https://github.com/erocarrera/pefile

Some more useful info by Didier Stevens
http://blog.didierstevens.com/2008/01/11/the-case-of-the-missing-digital-signatures-tab/
http://blog.didierstevens.com/programs/authenticode-tools/

http://forum.sysinternals.com/sigcheck-functionality_topic16893.html

**Comment by Maikuolan** [comment]
*Numerous other higher priorities at this time, and not a priority for the next major version release, `v1.0.0`. For now, closing and marking as abandoned. May revisit this proposal in the future for some later release, (`v1.1.0`, `v2.0.0`, etc).*
