### ISSUE TITLE
disable CLI mode for PHPUnit

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#46]
change 
https://github.com/Maikuolan/phpMussel/blob/39cb7c2358e8546b427b0c88dd3fa629afc4ce24/vault/phpmussel.inc#L12002 
to

```
if(!$MusselConfig['general']['disable_cli']&&function_exists('phpMusselFork')&&strlen(mussel_php)>0&&mussel_os=='WIN'&&mussel_sapi=='cli')
```

and add `disable_cli=1` (0 per default) in phpmussel.ini 

so we can run the PHPUnit tests in CLI mode like in the normal mode from the command line.

**Comment by Maikuolan** [comment]
Good idea.

Replying to this from my workplace at the moment, but I'll do that as soon as I get home later today.

**Comment by Maikuolan** [comment]
(( Also, I hadn't heard of PHPUnit before just now, but, I'm taking a look at it at the moment; Looks interesting! :-) ))

**Comment by DanielRuf** [comment]
PHPUnit and alternatives like JUnit for Java make testing code much easier with predefined tests and we can see if the code changes break or change the behaviour and the expected results differ.

Right, it is very helpful to have such tests and it improves the overall quality. Many projects use it with CI and if the tests fail they know it and the pull request or commit is not applied or they get some information what failed, like Travis CI does =)

**Comment by DanielRuf** [comment]
The new directive works like expected, I think we can close the issue.
