### ISSUE TITLE
False positives testing methods

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#47]
I've been thinking recently about what methods are available for testing phpMussel for false positives.

Testing how effective phpMussel is against a very specific malicious threat is easy enough - All we really need to do is try to scan samples of the malicious threat, file and etc, using phpMussel, to see whether or not it can be detected.

Somewhat trickier, however, is when a new detection method or new set of signatures is written, knowing precisely how reliable and safe that new detection method or new set of signatures is, and what the chances are of it resulting in false positives.

So far, with each new minor version release, I've ran a phpMussel scan against instances of `%root%/Windows/*` and `%root%/Program Files/*` directories known to be clean, to see if false positives were generated; This has been somewhat helpful, and I've found a few false positives in the past that have led to changes to the signatures and a few changes to the core code, but, this method is also extremely slow and tedious, and I'm not sure how reliable it actually is. One of the bigger problems with this method is in that phpMussel is ideally designed for webservers and websites, but not really targeted towards personal OS or desktop use anyhow, and so, testing in this way doesn't necessarily accurately reflect the types of files likely to be seen by phpMussel in actual deployment, nor does it necessarily accurately test for scalability.

Creating this issue as a way to let others know about this dilemma, to provide a place to discuss it and to hopefully generate some new ideas.

**Comment by DanielRuf** [comment]
I think it makes sense if we create some unit tests (which may run quite long) which scan the files of several CMS and other opensource PHP scripts.

I will prepare something for this.

**Comment by Maikuolan** [comment]
Awesome! That would be extremely helpful for this issue. :+1: :-)

**Comment by DanielRuf** [comment]
System specs:
OS: Win7
CPU: AMD Athlon 64 X2 5000+ (base core clock: 2600 MHz, 2 cores, 2 threads)
RAM: 8,00GB dual channel DDR2 @ 371MHz (6-6-6-18)

120MB/s connection
PHP 7.0.0 Apache module

curl download: 3.4690001010895
zip extract: 46.457999944687
teardown (recursive delte of extracted zip): 21.700999975204

setup script with teardown function:

``` php
// error_reporting(E_ALL);
// ini_set('display_errors', '1');
set_time_limit(0);

$cli=(substr(php_sapi_name(), 0, 3) === 'cli' ||(!empty($_SERVER['argc']) && is_numeric($_SERVER['argc']) && $_SERVER['argc'] > 0));

$start=microtime(true);

if($cli && empty($argv[1]))$url = $argv[1];
else if(!empty($_GET['url']))$url = $_GET['url'];
else $url = "https://github.com/drupal/drupal/archive/8.1.x.zip";
$file_array=explode("/",$url);
$file=array_pop($file_array);
if(file_exists("/".$file))unlink("/".$file);
$fp = fopen (dirname(__FILE__) . '/'.$file, 'w+');
$ch = curl_init(str_replace(" ","%20",$url));
curl_setopt($ch, CURLOPT_TIMEOUT, 50);
curl_setopt($ch, CURLOPT_FILE, $fp);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
if(curl_exec($ch) === false)
{
    // var_dump(curl_error($ch));
}
curl_close($ch);
fclose($fp);

echo microtime(true)-$start;
echo "<br>";

$files=array();
$za = new ZipArchive();

$start=microtime(true);

if ($za->open($file) === true) {
    $za->extractTo('test'); // @todo
    $za->close();
}

echo microtime(true)-$start;

function delTree($path) {
    $files=array();
    $objects = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path, RecursiveDirectoryIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST);
    foreach($objects as $name => $object){
        $object->isDir() ? rmdir($object->getRealPath()) : unlink($object->getRealPath());
    }
    rmdir($path);
}

function setup($url){ // @todo
    // downloadExtract($url);
}

function tearDown($path){ // @todo
    // delTree($path);
}
```

false positive scan file:

``` php
// error_reporting(E_ALL);
// ini_set('display_errors', '1');
set_time_limit(0);

/* @todo: wrap the code of this file in a function and call it in the mainfile
 * or parse a second parameter from the argument vector (argv) variable if the 
 * argument count (argc)is greater than 1
 */
require 'mussel/phpmussel.php';

$start=microtime(true);

$path="test";
$files=array();
$cli=(substr(php_sapi_name(), 0, 3) === 'cli' ||(!empty($_SERVER['argc']) && is_numeric($_SERVER['argc']) && $_SERVER['argc'] > 0));
$objects = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path, RecursiveDirectoryIterator::SKIP_DOTS), RecursiveIteratorIterator::SELF_FIRST);
echo "possible false positives:\n";
foreach($objects as $name => $object){
    if( !$object->isDir()){
        //32 = green, 33=red
        $scanResult=phpMussel("$name", false, true);
        if($scanResult==2){
            if($cli && empty($argv[1]) && ($argv[1]=="warning" || $argv[1]=="both") ){if($name!=="")echo "\033[32m$name\033[0m\n";}
            else if($cli){if($name!=="")echo "\033[31m$name\033[0m\n";}
            else echo "$name\n";
        }
        // echo hash_file("sha256", $name)."\n";
    }
}
echo microtime(true)-$start;
```

Took quite long on this relatively slow machine (5250.482216835 seconds, was working with it at the same time).

```

possible false positives:
test\drupal-8.1.x\core\authorize.php
***snip*** 1161 files flagged as false positive in total ***snip***
test\drupal-8.1.x\sites\example.settings.local.php
5250.482216835
```

A better machine and the upcoming phpMussel versions from the new repository should be much faster in theory.

I set `filetype_blacklist=''` for testing the script.

For example got this:

```
Thu, 31 Mar 2016 12:37:18 +0200 Started. > Checking 'test/drupal-8.1.x/core/lib/Drupal/Core/Ajax/AddCssCommand.php' (FN: 89c1d4bc; FD: c518b73b): -> Detected phpMussel-FN.X-05! Thu, 31 Mar 2016 12:37:18 +0200 Finished.
```

I don't know how much space and performance it would consume to generate filehashes of most available opensource scripts using `hash_file("sha256", $name)`, store it in the (sqlite) database and check the files before actually scanning them against the hashes.

In my opinion it makes no sense to prevent  or solve these false positives, there might be much much more.

When using the `hash_file` function, we can get the sha256 hashes quite fast:

```
8508011a7d462d9a70a0482cbb39cba473d30d12ffc21f527474645fda3980bc
*** snip *** 9704 sha256 filehashes in total *** snip ***
579ccf9a1f3910f9fd1bd8554144e4744fbc2e23e45ef084d9ceea23e680e33f
12.284228086472
```

raw size when saved as txt file: 626 KB
zip/tar gz: 348KB
bz2: 318KB

Currently our signatures are 42.2MB in size (latest release).

Probably it makes sense to create extra databases for the different content management systems, eCommerce scripts and so on and provide them as extra files (whitelist DB) which user can then also update using Composer. Maybe some helper script which detects the used CMS, eCommerce script, ... including the version information could be good.

Then it makes also sense to provide the generator script for the whitelist databases so users can create their own based on their used scripts to prevent false positives if they have too many of them.

What do you think about this?

**Comment by Maikuolan** [comment]
I suppose, if we provided a generator script for whitelisting, we wouldn't need to worry quite as much about false positives, so, this is definitely a good idea. :+1: 

I'm not so sure about actively managing our own whitelist DBs for this, though, due to the manageability issues of doing this (how frequently files are updated, deleted, created, changed, etc, and how much ongoing time it would require to keep lists like this up-to-date), but, if we wrote a good generator script with well-written instructions on how to use it correctly, we mightn't need any any external/additional whitelist DBs to be included anywhere anyway (because if the generator script can take care of it anyway, we could just instruct people to run that before scanning or something like that, maybe).

(..And I've only just noticed the time. I should probably get some sleep. I haven't yet looked closely at the above code, but I'll do that and reply to everything else a little later).

**Comment by Maikuolan** [comment]
> I suppose, if we provided a generator script for whitelisting, we wouldn't need to worry quite as much about false positives, so, this is definitely a good idea. :+1: 

..and SigTool now exists (although it doesn't yet produce any whitelist signatures; that's something for the future), so, issue no longer pertinent to this repository (any false positives in the future due to sets generated by SigTool can be sorted out there, and as for custom signatures, non-ClamAV signatures and so on, just taking extra care when creating new signatures should be adequate, considering the scope of the project). Marking as resolved and closing.
