### ISSUE TITLE
Wish list: Icon parsing.

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#5]
ClamAV is able to read and parse the icons of PE files and then check those icons against its database to help ascertain whether or not a particular PE file should be trusted.

phpMussel hasn't yet been coded to do this, and thus, at this time, can't make use of that part of the ClamAV signatures database.

Not a high priority, but, something that nonetheless would be cool to amend.

**Comment by DanielRuf** [comment]
Should be possible with `unpack` and other methods.

Maybe these repos give some idea:
https://github.com/enko/pe-header-extract
https://github.com/sjoorm/readpe
https://github.com/remfalc/pefilelib

http://stackoverflow.com/questions/2029409/get-version-of-exe-via-php

**Comment by DanielRuf** [comment]
I wrote a bit with Marc Ochsenmeier, the creator of pestudio and I think we can use some of the information retrieved by pestudio.

https://winitor.com

Future versions of pestudio will retrieve more information, which we could also use.

**Comment by Maikuolan** [comment]
*Numerous other higher priorities at this time, and not a priority for the next major version release, `v1.0.0`. For now, closing and marking as abandoned. May revisit this proposal in the future for some later release, (`v1.1.0`, `v2.0.0`, etc).*
