### ISSUE TITLE
Serialised Data

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#54]
**DanielRuf Wrote:**

> @Maikuolan We could use some array and serialize / unserialize it (store it serialized, so we have just one line in the logfile and can extract it for showing in the frontend without any problem. Some elements/values could contain some id representing the result (detected x ...).
> 
> Or just one line as a string, not serialized array.
> Should be better to read and analyze (think about delimiting the values with comma or tab or something else, so it can be easily inserted into spreadsheet software like Excel and easily analyzed).
> 
> But this could be another ticket/issue (custom log format).

---

On that note.. I actually wonder if maybe an additional logfile, separate from the others, should be created for this sort of thing? I like the idea of serialising/unserialising data for easy storage and access, and serialised data (for the caching) would be much easier to work with in regards to issues like this one (displaying scan results in the correct language when languages change), as would something like maybe CSV values or similar, but, the current logfiles (`scan_kills.txt`, `scan_log.txt`) were intended to be human readable without the need of additional tools or programs (as so that someone could read them simply by opening them), and if I change the way that those two logfiles are formatted (such as to be serialised, for example), it could potentially break human readability.

Seeing as those two logfiles can be disabled by omitting the `scan_log` and `scan_kills` directives anyhow, maybe a third logfile directive should be added (like `scan_serialized` or something similar)?

**Comment by DanielRuf** [comment]
You are right. The two current logfiles should be kept as they are and can be still used. 

Sure, as webdevelopers who are often reading logfiles (Apache, security solutions like ZBBlock and NinjaFirewall) which use one line per entry / result, not human readable text (eg in one line) is totally ok for us.

There has to be an easy to process logfile format for future plugins and further automatic processing.

I am for a third logfile format like you suggest. The serialized version (or encoded as JSON? what do you think?) should be the best solution. Any other script or plugin can then easily access the serialized data and for example a logfile plugin can generate custom logfiles based on user defined formats.

Just as an information, json_encode and json_decode is faster and JSON is supported by many tools.
http://stackoverflow.com/questions/804045/preferred-method-to-store-php-arrays-json-encode-vs-serialize

Or prefer serialize? Or support both (by adding an option for the used function based on the numeric value)?

I think serialize is enough (it is not much data to serialize / unserialize) and the performance should be ok.

We should plan this thoroughly before implementing this.

**Comment by Maikuolan** [comment]
Sorry for the slow reply; Busy past two days (and the phoneline problems have returned again, too). :-(

Agreed, we should plan this thoroughly before implementing this.

Reading the link you've supplied above, I think I'm leaning more towards `json_encode`/`json_decode`, but honestly, I'm still not absolutely certain which I'd prefer to use.

_Peter Bailey wrote:_

> By default, `json_encode()` converts UTF-8 characters to Unicode escape sequences while `serialize()` does not. **Note:** To leave UTF-8 characters untouched, you can use the option `JSON_UNESCAPED_UNICODE` as of PHP 5.4.

_and.._

> JSON will have no memory of what the object's original class was (they are always restored as instances of stdClass).

Currently, phpMussel doesn't make use of classes, so, I don't think this will matter much one way or the other. If UTF-8 conversions are reversible, then, that won't matter much, either, but, I think that would need to be tested, because, if they're not reversible, it would be a problem.

_KyleFarris wrote:_

> Excellent work dude. This will benefit everyone. I ran the test about 30 times and json_encode won every single time with around 100% (average) performance increase over serialize. I added json_decode and unserialize tests and json_decode won everytime in about 10 tests with an average performance benefit of ~20% over unserialize. Thanks for this.

_and.._

> Here we are almost 5 years later and I ran the tests again (just the json_encode) and it's averaging about 131% faster than serialize now. So, there must be some pretty nice improvements to that function in 5.4.x over 5.3.x. Specifically, I'm running 5.4.24 on CentOS 6. So, yay for JSON!!

Those considerations definitely make `json_encode`/`json_decode` appear very, very favourable; Those performance results are significantly superior to `unserialize`, if reliable.

_dreftymac wrote:_

> Too bad json_encode/json_decode is php 5.2 and above only. disgusts_uncover_akin_umbriel

I doubt many people these days would still be using PHP versions lower than 5.2, but, I know at least one or two hosting providers that do (though I don't recommend using them for various reasons), and ideally, it'd be best to avoid creating unnecessary problems with backwards compatibility if it's avoidable. If `json_encode`/`json_decode` provides significant advantage over `unserialize` (and it appears to do so), then, we could probably justify it easily enough, but, it is nonetheless a consideration.

Portability is always a big advantage (considering the primary reasons that we're thinking about adding this third logfile option for).

What do you think?

**Comment by DanielRuf** [comment]
Generally the PHP version should not be a big problem as there are many solutions for PHP before 5.2 which add JSON support.

Here are some of them:
http://stackoverflow.com/a/11684471
https://code.google.com/p/simplejson-php/
https://github.com/alexmuz/php-json
http://www.boutell.com/scripts/jsonwrapper.html
http://www.stetsenko.net/2009/09/php-json_encode-before-5-2-0/
http://stackoverflow.com/questions/2370968/how-can-i-decode-json-in-php-5-1

**Comment by Maikuolan** [comment]
This is next on my to-do list; I'll start looking at this soon.

**Comment by Maikuolan** [comment]
Attempted to write some code into the core script for logging serialised data and committed it a few minutes ago; It -partially- works, but it's buggy. Getting a little late tonight, but, I'm going to continue working on this in the morning.

I'll keep the branches separate for now, and merge back to master after everything seems to be working correctly.

**Comment by DanielRuf** [comment]
Ok, sounds good. Take the time you need. I wil help testing the and see if I can write some tests.

**Comment by Maikuolan** [comment]
Seems to be stable now, so, I've merged back to master and dropped the unneeded branches.

At the moment, logging serialised data won't work in CLI mode (I hope to eventually fix that), but, it seems to work correctly for normal file uploads.

**Comment by DanielRuf** [comment]
Ok, thanks for the update. I will take a look at it, test it and run the testsagain to see if there are any issues.

I will write some tests for testing the serialised data eventually.

**Comment by Maikuolan** [comment]
Technically now works in CLI-mode as of the most recent commit, but has room for improvement. Some of the data normally recorded in the serialised logfiles isn't available across separate execution scopes, so, the way that phpMussel forks its own process during scanning to keep individual scan tasks separate throughout the whole scan process would interfere with the ability to log this information using the serialised logfile format. The latest commit allows logging to now occur when scanning via CLI-mode, but the specific details about what has been detected will just show "Data not available" (for now). For now, if desperately needed, these entries (e.g., by using the start and finish timestamps) could be cross-referenced against entries in the standard logfiles to retrieve this more detailed information, I guess.

Fixing the problem of availability of this information across execution scopes would require a significant rewrite of code as it stands at the moment, but, that'll likely happen eventually anyhow, so, it's still on the to-do list.

Anyhow, seeing as, technically speaking, this feature has now been implemented across all scan modes for phpMussel, I'll mark it as implemented and close.
