### ISSUE TITLE
Correctly parsing filenames in CLI-mode bug

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#61]
I found a bug relating to the ability of phpMussel to correctly parse non-ANSI/non-ASCII filenames in CLI-mode when recursively scanning directories.

Filenames aren't currently being parsed correctly, resulting in mangled filenames appearing in the scan_log and/or files not consequently being found by phpMussel after searching a directory, resulting in scan entries being listed as "invalid files".

I don't currently have a fix for this issue.

I'm creating this issue here to track progress.

I believe the bug relates to the way in which Windows encodes filenames based upon code page tables, to the way in which PHP consequently reads and handles non-ANSI/non-ASCII filenames, and in phpMussel not accounting for a difference that exists between those two, resulting in the inconsistent reading of non-ANSI/non-ASCII filenames.

Some things I found online:

http://stackoverflow.com/questions/18204364/php-upload-utf-8-filename
http://stackoverflow.com/questions/15684348/cant-read-utf-8-file-names
http://stackoverflow.com/questions/2050973/what-encoding-are-filenames-in-ntfs-stored-as/2051018#2051018

This bug doesn't affect phpMussel when used for servers or websites.

**Comment by Maikuolan** [comment]
Just re-tested this against all versions of PHP that phpMussel currently supports, and the bug doesn't seem to affect any PHP versions >= `7.1.0`. Looking at the [PHP7 Changelog](http://php.net/ChangeLog-7.php), I noticed this entry listed for the `7.1.0` release (2016.12.01):

> Fixed UTF-8 and long path support on Windows.

So I guess, for the latest versions of PHP at least, this bug could be considered already "fixed".

I've basically ignored this since 2015 due to working on other things, but I'll start looking at a proper fix (for older PHP versions) later today.

**Comment by Maikuolan** [comment]
Windows uses too many different types of encodings, filenames can have mixed encodings, using the wrong one when trying to convert between them all can cause fatal errors, there's no real easy way to test which is being used for any given filename without actually attempting to convert it, and the bug literally only affects specifically Windows users using CLI-mode on PHP < `7.1.0` (i.e., users using OS other than Windows, using phpMussel for purposes unrelated to CLI-mode, and using PHP >= `7.1.0`, aren't affected by this), so, I'm thinking I can just mark this as a *won't fix*.

Not saying it's impossible to fix this bug, but I haven't found a viable and straightforward way to do it yet (I've been playing around with *iconv* a bit, but haven't really gotten anywhere with it), so, I suspect it would probably take a fair bit more time and research to fix it properly anyhow. On the other hand, the very small number of users affected by it, should be in a position whereby it should be exceptionally easy to just update their PHP version, or run a separate instance of PHP specifically for phpMussel, and updating PHP to (or running phpMussel with) a version >= `7.1.0` will solve the problem anyhow. So, moving on (and one step closer to finishing off the `v1.0.0` checklist).

The solution, for those affected by this bug: Update your PHP.

**Comment by nhlm** [comment]
Just a note: https://msdn.microsoft.com/de-de/library/windows/desktop/dd317748(v=vs.85).aspx
