### ISSUE TITLE
I can help you translate Simplified Chinese Documents

### ISSUE THREAD

**Issue by zxzllyj** [phpMussel/phpMussel#64]
I see from the www.oschina.net you want to translate your documents into simplified Chinese, I think I can help you get the job done.

**Comment by Maikuolan** [comment]
@zxzllyj Yes, I do. The help would be greatly appreciated! :-)

Also, are you "独孤青冥" (because of possible multiple replies)?

**Comment by Maikuolan** [comment]
_Reference: http://my.oschina.net/Maikuolan/tweet/6621647_

**Comment by zxzllyj** [comment]
yes，You know, github does not support Chinese Username，so....

**Comment by Maikuolan** [comment]
Yeah.. Lack of support is unfortunate. '^.^

Anyhow, thanks for helping. :-)

**Comment by Maikuolan** [comment]
@zxzllyj I tried making a pull request today, but, GitHub said there were merge conflictions (I think, because of some intermediary commits I made earlier; sorry for that). x_x

It's no problem though; I've manually merged your current changes, so, everything should be there now. May need to re-fork, though, to resolve the conflictions.

And thanks again. :-)

**Comment by zxzllyj** [comment]
After this, I do all the work again push it (from Google Translate)

**Comment by Maikuolan** [comment]
@zxzllyj Any updates? :-)

**Comment by zxzllyj** [comment]
It's finished, you can download the translated file separately and then update it to your new version. It's so sorry for so long, because I don't have a computer in my spare time. I can only use working hours.I think, every boss is not in favor of the staff to do other things at work

**Comment by Maikuolan** [comment]
:+1: 

It's okay, and thanks for the help; It's greatly appreciated. :-)

I'll implement the changes tonight.

**Comment by Maikuolan** [comment]
Implementation complete. :-)
