### ISSUE TITLE
Quality Assurance (duplicate code and other things)

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#7]
It seems there are some code parts duplicate and the conditions can be merged, because the checks for the magic number and the extension use the same code:

https://github.com/Maikuolan/phpMussel/blob/5a52600f77dc26ad16671287e704e57afab094dd/vault/phpmussel.inc#L11743
https://github.com/Maikuolan/phpMussel/blob/5a52600f77dc26ad16671287e704e57afab094dd/vault/phpmussel.inc#L11726

https://github.com/Maikuolan/phpMussel/blob/5a52600f77dc26ad16671287e704e57afab094dd/vault/phpmussel.inc#L11734
https://github.com/Maikuolan/phpMussel/blob/5a52600f77dc26ad16671287e704e57afab094dd/vault/phpmussel.inc#L11751

**Comment by Maikuolan** [comment]
Not without reason in this instance, but yeah, that's code duplication there. :-/

The code being used is the same, but the reason for splitting the conditions like that is that phpMussel needs to attempt to decompress files based upon the presence of magic numbers -before- trying to decompress files based upon file extensions, the idea being that magic numbers should be the primary indicator of the type of compression used and file extensions should be a fall-back indicator if there isn't any valid magic numbers found to be present. This is to avoid potential attackers trying to trick phpMussel by simply changing the file extension of a compressed file from one extension type to another (which could result in phpMussel declaring a malicious file as safe).

Still would be good to reduce on duplication if at all possible, though. I think there were a other areas of the script that were similar in that way.

**Comment by DanielRuf** [comment]
At least they share almost the same code, which can be further optimized as a parameterized method:
![image](https://cloud.githubusercontent.com/assets/827205/7788179/5dfcb968-0231-11e5-818f-3c0884ae1b6e.png)

I will use this issue to report my future findings and commit fixes when I have setup Scrutinizer and other tools.

For reference: http://phpqatools.org/

I have checked phpmussel.inc with some tools.
The results can be directly downloaded from https://gist.github.com/DanielRuf/b5016ebd4ffd6d97ddc2/download

https://gist.github.com/DanielRuf/b5016ebd4ffd6d97ddc2

I will manually check / revise the issues found in the reports and make proposals for better solutions so we can save some lines and codeparts.

**Comment by Maikuolan** [comment]
Attempting to merge some signature sections of the core script at the moment; If everything goes according to plan, the next commit should see roughly a ~15% reduction in the filesize of `phpmussel.inc`.

**Comment by Maikuolan** [comment]
*Old issue. Closing. We can reopen or create a new issue in the future if necessary.*
