### ISSUE TITLE
Support multiple file upload

### ISSUE THREAD

**Issue by BugBuster1701** [phpMussel/phpMussel#74]
I tried phpMussel in the CMS Contao, but:

`Unauthorised file upload manipulation detected (Array)`

Contao uses a form with support for multiple file upload.

`<input multiple="" name="files[]" type="file" />`

Output of the variable `$ _FILES` when you select a single file in Contao:

```
Array
(
    [files] => Array
        (
            [name] => Array
                (
                    [0] => 4advent.jpg
                )
            [type] => Array
                (
                    [0] => image/jpeg
                )
            [tmp_name] => Array
                (
                    [0] => /tmp/phpVCuBLR
                )
            [error] => Array
                (
                    [0] => 0
                )
            [size] => Array
                (
                    [0] => 22706
                )
        )
)
```

For comparison, a form that support only to upload a single file has this output (example):

```
Array
(
    [files] => Array
        (
            [name] => 4advent.jpg
            [type] => image/jpeg
            [tmp_name] => /tmp/phpOX0RwZ
            [error] => 0
            [size] => 22706
        )

)
```

**Comment by Maikuolan** [comment]
Based on this information, I've been able to replicate the problem on my end, so, marking this a a bug.

Thanks for letting us know. :-)

Working on this bug now. I'll reply again when I've got it fixed (shouldn't take too long; couple of hours, maybe).

![confirmed](https://cloud.githubusercontent.com/assets/12571108/11176023/ec751420-8c73-11e5-89fb-6d5265b43da6.png)

**Comment by Maikuolan** [comment]
A little later than I'd planned, but, the latest commit should resolve the issue (hopefully).

I've tested the latest commit on my end, and I can't seem to replicate the problem anymore; Could you test it on your end (the latest commit), and let me know if the problem persists? Cheers. :-)

**Comment by BugBuster1701** [comment]
:+1: multiple file uploads are ok now.
