### ISSUE TITLE
RTL text in markdown.

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#78]
I have someone working on the Arabic translations for phpMussel (both the documentation and the language data), and they're about halfway through finishing it all.

They're sending their work to me as they complete it as Microsoft Word files, and everything looks mostly okay in the Microsoft Word files.

However, trying to then translate this work into markdown format, so that I can upload it to the GitHub repository, is proving to be rather difficult (for me, at least).

I mostly edit markdown files using Notepad++, and after some tinkering (note that this is the first time I've ever needed to work with right-to-left text in Notepad++), I've discovered that I can change the document text direction by using Ctrl+Alt+R (for right-to-left) and Ctrl+Alt+L (for left-to-right). Yay!

This saves me from a lot of trouble, because the behaviour of RTL and LTR characters in Notepad++ seems very inconsistent to me (I read about how to use these characters from the Unicode website, so, I'm hoping this information in correct, but maybe I'm doing something wrong, something that Notepad++ doesn't like; anyhow, because I can just use Ctrl+Alt+R, this doesn't really matter).

![n](https://cloud.githubusercontent.com/assets/12571108/11317987/0570a460-907c-11e5-8b7d-498bae5c3207.png)

So far, so good.

But then I try to preview my markdown using the GitHub in-built file editor:

![markdown](https://cloud.githubusercontent.com/assets/12571108/11317991/1c9ff7c6-907c-11e5-84e8-7fd8e7e2dddf.png)

Everything becomes messed up, and looks similar to how it looks in Notepad++ when using the incorrect document text direction.

I'm not sure how to fix this, and I'm seeking advice.

Is there not any way using markdown code to identify text direction or overall document text direction? I tried Googling for help, briefly looked on Stack Exchange, and I looked at the mastering markdown page here on GitHub, but I couldn't work it out.

**Comment by DanielRuf** [comment]
I read that GitHub does not support rtl in Markdown directly until today.

But you can try HTML in the md files. Never tried this.

https://github.com/github/markup/issues/332

**Comment by Maikuolan** [comment]
I wasn't aware that `<div>` could be used within markdown code; That's definitely useful to know!

Thanks for that link; I copied the idea mentioned by Alshurafa in the linked issue, and, success! It seems to work :-)

2/8 sections of the translation are now completed and available, and I've been told by the translator that the remaining sections should be finished soon.

Seeing as the text direction issue seems to be resolved now, I'll close this issue.

**Comment by Maikuolan** [comment]
I've encountered a new but related problem do to with RTL/LTR formatting, so, I think I need to reopen this issue, at least, for now.

In the **[Arabic documentation](https://github.com/Maikuolan/phpMussel/blob/master/_docs/readme.ar.md)** (7/8 sections are now fully translated), if you search for "التوزيع التفصيلي للتوقيع", there's a list of the different types of signatures supported by phpMussel, what they are, how they work, etc. Due to content of some of the items on that list, which begin and end with RTL text but have some small amount of LTR text embedded in the middle, some parts of some of those lines (although the translations themselves are 100% accurate), aren't displaying correctly and aren't as intelligible as they should be.

(The problem demonstrated in the below attached image):

![alignment](https://cloud.githubusercontent.com/assets/12571108/12230748/5e9bf7a4-b88d-11e5-8f90-dd02921301d5.png)

I suspect the solution may involve some manner of shenanigans with DIVs/SPANs/etc, but, I'm not entirely sure how to resolve this problem, or what the best approach would be.

**Comment by DanielRuf** [comment]
Interesting, and seems to be challenging. I am not sure how to solve this (and if this can be solved in mardown). You could experiment with the different markup with a Gist or in a separate repository, maybe there is an easy solution for this, but I think this has to do with the markdown parser?

Some related information about bidirectional text here: http://talk.commonmark.org/t/explicit-rtl-indication-in-pure-markdown/286/9

Seems span inside of div makes sense but did not try this so far.

**Comment by Maikuolan** [comment]
The version of the Arabic translation for the README which currently exists in the unstable branch doesn't seem to have this problem anymore, due to some changes I've been working on for the READMEs (removing references to specific signature files and such, due to the planned move to store signature files in a separate repository in the future).

I don't think this problem will persist anymore once everything has been safely merged. Closing this issue.
