### ISSUE TITLE
PSR

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#80]
### **PSR Checklist**

_Entries will be marked upon being completed and committed to the master codebase._

---

**[PSR-1](http://www.php-fig.org/psr/psr-1/)**

_The following markable items must be implemented._
- [x] Files MUST use only `<?php` and `<?=` tags.
- [x] Files MUST use only UTF-8 without BOM for PHP code.
- [x] Files SHOULD either declare symbols (classes, functions, constants, etc.) or cause side-effects (e.g. generate output, change .ini settings, etc.) but SHOULD NOT do both.

_phpMussel versions/releases <1.0.0 don't use classes, so, the following four PSR-1 items aren't relevant for versions/releases <1.0.0; There's nothing to mark here. Any class-based phpMussel versions/releases =>1.0.0 WILL use classes, so, the following four PSR-1 items will BECOME relevant for versions/releases =>1.0.0; We will ensure that we adhere to these items during class implementation and thereafter (this should be completed prior to any official =>1.0.0 version/release)._
- Namespaces and classes MUST follow an "autoloading" PSR: [PSR-0, PSR-4].
- Class names MUST be declared in StudlyCaps.
- Class constants MUST be declared in all upper case with underscore separators.
- Method names MUST be declared in camelCase.

---

**[PSR-2](http://www.php-fig.org/psr/psr-2/)**
#### 1. Overview.

_The following markable items must be implemented._
- [x] Code MUST follow a "coding style guide" PSR [[PSR-1](http://www.php-fig.org/psr/psr-1/)].
- [x] Code MUST use 4 spaces for indenting, not tabs.
- [x] There MUST NOT be a hard limit on line length; the soft limit MUST be 120 characters; lines SHOULD be 80 characters or less.

_The following non-markable items relate to the implementation of classes, which versions/releases <1.0.0 don't use; This item, therefore, isn't currently relevant, but will BECOME relevant from versions/releases =>1.0.0 and thereafter. We will ensure that we adhere to these items during class implementation and thereafter (this should be completed prior to any official =>1.0.0 version/release)._
- There MUST be one blank line after the `namespace` declaration, and there MUST be one blank line after the block of `use` declarations.
- Opening braces for classes MUST go on the next line, and closing braces MUST go on the next line after the body.
- Visibility MUST be declared on all properties and methods; `abstract` and `final` MUST be declared before the visibility; `static` MUST be declared after the visibility.

_The following markable items must be implemented._
- [x] Control structure keywords MUST have one space after them; method and function calls MUST NOT.
  _Reference: [php.net/manual/en/language.control-structures.php](http://php.net/manual/en/language.control-structures.php)_
- [x] Opening braces for control structures MUST go on the same line, and closing braces MUST go on the next line after the body.
- [x] Opening parentheses for control structures MUST NOT have a space after them, and closing parentheses for control structures MUST NOT have a space before.
##### 2.1 Basic Coding Standard
- [x] Code MUST follow all rules outlined in [PSR-1](http://www.php-fig.org/psr/psr-1/).
##### 2.2 Files
- [x] All PHP files MUST use the Unix LF (linefeed) line ending.
- [x] All PHP files MUST end with a single blank line.
- [x] The closing `?>` tag MUST be omitted from files containing only PHP.
##### 2.3 Lines
- [x] There MUST NOT be a hard limit on line length.
- [x] The soft limit on line length MUST be 120 characters; automated style checkers MUST warn but MUST NOT error at the soft limit.
- [x] Lines SHOULD NOT be longer than 80 characters; lines longer than that SHOULD be split into multiple subsequent lines of no more than 80 characters each.
- [x] There MUST NOT be trailing whitespace at the end of non-blank lines.
- [x] Blank lines MAY be added to improve readability and to indicate related blocks of code.

_Writing that we MAY do something, but NOT writing that we MUST do something; I think this can be marked by default..?_
- [x] There MUST NOT be more than one statement per line.
##### 2.4 Indenting
- [x] Code MUST use an indent of 4 spaces, and MUST NOT use tabs for indenting.
##### 2.5 Keywords and True/False/Null
- [x] PHP **[keywords](http://php.net/manual/en/reserved.keywords.php)** MUST be in lower case.
##### 3. Namespace and Use Declarations

_phpMussel versions/releases <1.0.0 don't use `namespace` or `use`, so, the following non-markable items aren't relevant for versions/releases <1.0.0; Any class-based phpMussel versions/releases =>1.0.0 WILL use `namespace` (and possibly will use `use`), so, the following non-markable items will BECOME relevant for versions/releases =>1.0.0; We will ensure that we adhere to these items during development of 1.0.0 and thereafter (this should be completed prior to any official =>1.0.0 version/release)._
- When present, there MUST be one blank line after the `namespace` declaration.
- When present, all `use` declarations MUST go after the `namespace` declaration.
- There MUST be one `use` keyword per declaration.
- There MUST be one blank line after the `use` block.
##### 4. Classes, Properties, and Methods

_This will be addressed by phpMussel version/release 1.0.0; This won't be relevant for prior versions/releases._
##### 5. Control Structures
- [x] There MUST be one space after the control structure keyword
- [x] There MUST NOT be a space after the opening parenthesis
- [x] There MUST NOT be a space before the closing parenthesis
- [x] There MUST be one space between the closing parenthesis and the opening brace
##### 6. Closures
- [x] Closures MUST be declared with a space after the function keyword, and a space before and after the use keyword.
- [x] The opening brace MUST go on the same line, and the closing brace MUST go on the next line following the body.
- [x] There MUST NOT be a space after the opening parenthesis of the argument list or variable list, and there MUST NOT be a space before the closing parenthesis of the argument list or variable list.
- [x] In the argument list and variable list, there MUST NOT be a space before each comma, and there MUST be one space after each comma.
- [x] Closure arguments with default values MUST go at the end of the argument list.
- [x] Argument lists and variable lists MAY be split across multiple lines, where each subsequent line is indented once. When doing so, the first item in the list MUST be on the next line, and there MUST be only one argument or variable per line.
- [x] When the ending list (whether or arguments or variables) is split across multiple lines, the closing parenthesis and opening brace MUST be placed together on their own line with one space between them.

---

**[PSR-3](http://www.php-fig.org/psr/psr-3/)**

_This will be addressed begin exploring a classful implementation in the future._

---

**[PSR-4](http://www.php-fig.org/psr/psr-4/)**

_This will be addressed begin exploring a classful implementation in the future._

---

**[PSR-6](http://www.php-fig.org/psr/psr-6/)**

_This will be addressed begin exploring a classful implementation in the future._

---

**[PSR-7](http://www.php-fig.org/psr/psr-7/)**

_This will be addressed begin exploring a classful implementation in the future._

---

---

I've recently been reading through the [PSR](http://www.php-fig.org/) guidelines for PHP standards, and, although I have mixed feelings about some of their guidelines, I'm going to try to adopt at least some of them.

In particular, in [PSR-2](http://www.php-fig.org/psr/psr-2/), under **2.2 Files**, they write:

> The closing `?>` tag MUST be omitted from files containing only PHP.

This, principally, is something I've never liked doing, due to that for most programming languages, generally, anything opened should always be closed, and code should generally follow a logical order and be contained within a logical hierarchical tree (at least, so I've always read and so I've always been led to believe).

Currently, phpMussel always closes its PHP (and so, doesn't omit any closing PHP tags).

**[Here](http://www.sitepoint.com/should-you-close-your-php-code-tags/)** is an interesting article, where the author has posed the question of whether or not we should omit closing tags, and some of the comments (although many of them are now more than a few years old) are very interesting. There seem to be people with very strong views on both sides of the fence, and although many of these views contradict each other, I think many of them, on both sides, have valid points.

Minimising the risk of accidentally inserting bugs or errors in the future is definitely a good thing, but I've always felt that correctly closing any opened tag seemed more professional, so, I was at odds about this.

So, to omit, or not to omit; That is (or was..) the question.. Until I found **[this](http://php.net/manual/en/language.basic-syntax.phptags.php)**:

> If a file is pure PHP code, it is preferable to omit the PHP closing tag at the end of the file. This prevents accidental whitespace or new lines being added after the PHP closing tag, which may cause unwanted effects because PHP will start output buffering when there is no intention from the programmer to send any output at that point in the script.

Considering it's also recommended on the PHP site itself to omit closing tags for pure PHP files (and I wasn't aware of this until just now), I think this is a change I'll need to implement for phpMussel.

Under the same section, they also write this:

> All PHP files MUST end with a single blank line.

phpMussel doesn't currently do this, for the very reason that including any whitespace after a closing PHP tag could result in headers being prematurely sent, and this is something we don't want happening. However, if I'm to remove the closing PHP tags, then, appending the extra newline to the end of PHP files is something that can be easily done (because the risk of headers being prematurely sent won't be there anymore).

> All PHP files MUST use the Unix LF (linefeed) line ending.

This, we're already doing (as well as quite a few other things recommended, though not everything); Figured that one out a long time ago, before I'd ever heard of PSR. :+1: 

Anyhow. There's a lot to read through, and a lot to do to here, so, this may be in multiple commits, but, it's something to do nonetheless. Posting this as an issue for until this is done.

**Comment by DanielRuf** [comment]
Great, the PSRs are very helpful to improve the overall code quality and readability. Right, this has to be done in little steps.

**Comment by Golpha** [comment]
Something technical:

Its all about the context. The PSR-Standard and the PHP Group suggests to omit the closing part of the processing instruction ( `<?...?>` is naturally a processing instruction and NOT a tag by design ) to avoid upper context related failures. PHP code should always live separated from other sources due to separation of concerns principle ( like html, xml, svg or whatever you try to generate ), to make that clear for a better understanding: you may ( and should ) threat the `<?php` as a heading notation ( like a shebang ), that declares the script as a php script, instead of a string that is wrapped into a tag ( or the expression content of a processing instruction in case of the php open "tag" ).

 I know that it is hard(er) to drop long-therm habits, but i do recommend to enforce the PSR Coding Standard as it comes. It is a contracted format of source code to grant the best possible interop experience for all contributors.

The line-ending is fixed on push, when git is properly configured. Nothing to fight with inside of the IDE / Editor of your choice.

**Comment by Maikuolan** [comment]
Sounds good, and I agree. :+1: 

It may take time, because there are still many things that don't entirely conform, but, I think, this is definitely something that should be worked on.

So far, most of what I've read seems to make sense, but, I am nonetheless very new to PSR, so, help and guidance is always welcomed. :-)

**Comment by Golpha** [comment]
Applying PSR Standards to phpMussel opens the possibility to being enlisted at: https://github.com/ziadoz/awesome-php#security

I think, that should be a reachable goal for the future.

**Comment by Maikuolan** [comment]
Absolutely. That would be great. :-)

**Comment by Maikuolan** [comment]
_Added a PSR checklist to the initial post of this issue._

**Comment by Maikuolan** [comment]
There will be more aspects of PSR to address with future releases (such as for phpMussel =>v1.0.0, when we implement classes and various other discussed ideas), <strike>but, for now, I _believe_ the current codebase should be compliant</strike>. Because many PSRs deal with classes, and the current codebase doesn't use classes, most PSRs aren't yet relevant (but will become relevant from =>v1.0.0). The most important PSRs for the current pre-v1.0.0 codebase (internally marked as v.0.10.0 at this time), for now, are PSR-1 and PSR-2.

<strike>If either of you (or anyone else reading this) has the spare time to do so, I'd love there to be a quick look-over of the current codebase to ensure that my interpretation of PSR-1 and PSR-2 were correct, and to ensure that the current codebase, is, in fact, compliant (generally speaking and for the most part). :-)</strike>

Edit: I believe the current codebase should be compliant, _except for the phpMussel_mail() function, starting from functions.inc:L8369 (`// AAA urlscanner functionality for phpMussel_mail() BEGIN`) and ending at functions.inc:L8537 (`// AAA urlscanner functionality for phpMussel_mail() END`), which isn't yet compliant; I'll sort that part out soon._

**Comment by DanielRuf** [comment]
Great =)

**Comment by Maikuolan** [comment]
Marking as completed and closing.

Will reopen this when we begin exploring a classful implementation in the future.
