### ISSUE TITLE
Superfluous text files in repo.

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#84]
I'm creating this issue here in hope that some users may reply here, to let us know how they feel about this. I'll leave this issue open either until the next release or until a definite decision is reached.

_Issue mirrored at http://www.spambotsecurity.com/forum/viewtopic.php?f=57&t=3781_

---

With the README documentation, because I'm currently maintaining two different formats for them (the plain-text files and the markdown files), as more translations into different languages are being completed and as more information is added to the README documentation, it's slowly becoming more tedious and time-consuming to maintain it all, and so, I've been contemplating the possibility of ditching the plain-text README files entirely in favour of just maintaining the markdown README files.

Currently, the README documentation consists of 23 files and has a footprint of 2.20 MBs; If I ditched the plain-text README files in favour of just maintaining the markdown README files, that would reduce to 13 files and 1.19 MBs (at this time; in either way, before and after, those numbers are still likely to grow as more data is added and/or more translations are completed).

Originally, I wanted to maintain both formats, to give the users the benefit of choice as to which they'd prefer to use: The markdown files will always be easier to use and read when reading them via a program or service that can process them (such as GitHub), but, in the absence of such a program or service, the plain-text files will always be easier to read, simply because they're "plain" and your eyes won't need to distinguish between the machine-readable formatting and the actual human-readable text. In this regard, there is still benefit to maintaining both formats (plain-text and markdown), but, maintainability is starting to become an issue, especially when there are big changes that require changing parts of the README documentation, which can slow down any progress for later, future changes.

So, on this note, I want to ask some quick questions of any of you that are using phpMussel at the moment:
- In the overall context of your using phpMussel, how important do you feel these plain-text files are?
- Given the choice of using one or the other, would you prefer the plain-text files or the markdown files?

Additionally, for the same reasons of maintainability, I've been contemplating the possibility of removing the signatures tally file. This file was originally created to allow users to know where the signatures come from (because there are multiple sources), and to know exactly how many signatures each release contains, where they come from, which signature files have changed and precisely how much change has occurred. It's yet another thing that can be a little tedious to maintain, too, and can slow down progress sometimes. So, in regards to that file, too, I would like to ask:
- Do you use the signatures tally?
- In the overall context of your using phpMussel, how important do you feel the signatures tally file is?
- Would it bother you if it was removed from future releases?

Your responses will help.

Thanks. :-)

---

_Footnote for the other devs / the team: As discussed earlier, if we kept to manually maintaining only one format, then, for other formats, if we wanted them, we could possibly implement some type of automatic generation/conversion of the READMEs into these different formats, possibly to be kept in some external repository and included as a submodule, if necessary. This is also something we can discuss and explore._

**Comment by DanielRuf** [comment]
> Do you use the signatures tally?

No

> In the overall context of your using phpMussel, how important do you feel the signatures tally file is?

As it might change often and most won't or can't read / understand it, not so important imho.

> Would it bother you if it was removed from future releases?

Personally no.

**Comment by Maikuolan** [comment]
Cool. I think I'll remove them, then. :+1: 

(I'll leave the issue open for another 24 hours, in case anyone else wants to reply to add any new perspective to this, and then I'll close it).
