### ISSUE TITLE
@package tag.

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#85]
Should this be kept in the package, or should we ditch it?

In reference to this: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1833#issuecomment-198941180

> This is intended since `@package` has no use in today's php apps. It was only ever meant to be used to simulate namespaces on php 5.2.

I'd always been under the impression that the `@package` tag was (considering this is related to phpDocs) purely for documentation, and had no functional purpose, but that it would be required by phpDocumentor and similar phpDoc-based documentors (Doxygen, etc) for correctly grouping related files and structural elements together.

I've seen plenty of examples across GitHub of modern, up-to-date packages that still make use of the package tag, but it seems that PHP-CS-Fixer, at least, disagrees with using the package tag.

Documentation for the package tag on the phpDocumentor website: https://www.phpdoc.org/docs/latest/references/phpdoc/tags/package.html

> The `@package` tag can be used as a counterpart or supplement to Namespaces. Namespaces provide a functional subdivision of Structural Elements where the `@package` tag can provide a logical subdivision in which way the elements can be grouped with a different hierarchy.
> 
> If, across the board, both logical and functional subdivisions are equal is it NOT RECOMMENDED to use the `@package` tag, to prevent maintenance overhead.

Considering our minimum required PHP version for phpMussel is 5.4.0 (which supports namespaces), does this mean we should ditch the package tag? Would like to know what you think.

@DanielRuf @Golpha

**Comment by DanielRuf** [comment]
I would definitely prefer namespaces over the package tag.

**Comment by Maikuolan** [comment]
Cool, cool.

Mostly, I thought the package tags should be there for the benefit of documentation tools such as phpDocumentor, Doxygen, etc, but if these tools don't actually _need_ this tag to exist in a package in order to be able to categorise the elements of the package (eg, if they're able to determine how to correctly categorise everything based on the presence of a namespace keyword), then, there really wouldn't be much - if any - point in keeping the package tag at all.

It's just tricky though, in that the documentation itself isn't absolutely 100% clear on this point.

**Comment by DanielRuf** [comment]
> It's just tricky though, in that the documentation itself isn't absolutely 100% clear on this point.

It may be that these parts are a bit outdated or mention that the tag and namespaces are supported but the second is preferred for new and current projects using supported PHP versions (5.5+ currently).

**Comment by Golpha** [comment]
package tags are only for api-doc-related coordination. No api-docs, no need for a package tag.

**Comment by DanielRuf** [comment]
> package tags are only for api-doc-related coordination. No api-docs, no need for a package tag.

Thanks for the clarification. So we don't need this (so far).

**Comment by Maikuolan** [comment]
Cool. :+1: 

In that case, I'm thinking that because we already have the README documentation available, separate api-docs probably aren't required, and therefore, it makes sense to drop the package tag (at least, for now).

I'll keep this issue open for another 24 hours, in case there are any objections or in case anyone else wants to add anything, and if there aren't any objections, I'll close the the issue and drop the package tags. :-)
