### ISSUE TITLE
Donation link broken?

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#86]
There's been a report (**[here](http://www.spambotsecurity.com/forum/viewtopic.php?f=58&t=3812&p=26060)**) that the PayPal donate button for phpMussel (**[here](http://maikuolan.github.io/phpMussel/)**) could be broken or inoperable for some people.

I tested this just now by clicking on it myself, and it loaded the PayPal donate page without any problems.

Would others be able to try clicking on the button to test it, and confirm here whether it's working?

(Don't need to actually donate anything, of course; You can load the donate page, but there won't be any commitment to a donation unless an amount is entered and submitted after having logged into PayPal; Need to know, though, whether the button is actually working for other people, due to this report that apparently it isn't).

**Comment by DanielRuf** [comment]
No problem here
![image](https://cloud.githubusercontent.com/assets/827205/13906281/03fa1b88-eed3-11e5-8758-18e65527e80a.png)

**Comment by Maikuolan** [comment]
Awesome. :+1: 

The screenshot looks as it's supposed to look (I see the same thing on my end).

I'm curious why it isn't working for the user reporting the problem.. Javascript problem, maybe?

**Comment by DanielRuf** [comment]
If it is a problem with JavaScript or the rendering engine of the browser, we need more information like browser vendor, browser version, plugins / extensions, output of the browser console, operating system, ...

**Comment by Maikuolan** [comment]
The person that originally reported the problem has replied back; It seems to be a problem with rendering using Safari.

**Comment by DanielRuf** [comment]
Safari on Windows (not available anymore), or Mac OS X, or iOS?

**Comment by Maikuolan** [comment]
Good question! Not sure, but I'll see if I can figure it out.

**Comment by Maikuolan** [comment]
According to **[Wikipedia](https://en.wikipedia.org/wiki/Safari_version_history)**, Safari "6.1.6" was released August 13, 2014, and the current latest version of Safari is (although only released 2 days ago) "9.1", meaning that his version of Safari is now three major versions behind.

Considering that, I'm thinking at the moment that the best bet here would be to either find someone using the latest version or install the latest version somewhere and test to see if the problem persists, and if it does, we've got a browser cross-compatibility problem, but if it doesn't, it's probably some issue with the old version that's been solved and so we could close this issue.

I'm going to ask around to see if I can find someone to test this.

(I had a quick search on Google for online cross-compatibility testing tools, and it turned up a few results, but nothing for the latest versions of Safari; Using Windows myself, so, I couldn't test it directly myself at the moment).

**Comment by Maikuolan** [comment]
Yep, confirmed; This seems to be a problem with the older version of Safari.

I had a friend via Facebook test this using the latest version of Safari, and the problem doesn't seem to persist with his browser.

Safari "6.1.6":

![screen shot 2016-03-20 at 3 32 44 pm](https://cloud.githubusercontent.com/assets/12571108/13977043/8ba9f75e-f100-11e5-92ba-8ee2b3549d8e.jpg)

Safari "9.1":

![12516415_874279702683260_379271959_n](https://cloud.githubusercontent.com/assets/12571108/13977048/95f6c304-f100-11e5-8557-8aca7e4b4413.jpg)

I'll close this issue. :+1:
