### ISSUE TITLE
wrong blocksize in $phpMussel['ReadFile']

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#89]
The DocBlock parameter for $s says 48KB, but 131072 bytes are 128KB

https://github.com/Maikuolan/phpMussel/blob/master/vault/functions.php#L587

It could be also useful to add another parameter $blocksize which is used, the default value is used in the code and developers can define a value if needed.

**Comment by Maikuolan** [comment]
Good catch, and good point. :+1: 

I'll add this in now.

**Comment by Maikuolan** [comment]
(Got a little side-tracked earlier, but the change has now been committed).

**Comment by DanielRuf** [comment]
No problem =)
