### ISSUE TITLE
suggestion: alternative setup

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#9]
We can also use php.ini, user.ini or .htaccess with the auto_prepend_file directive of Apache

`php_value auto_prepend_file absolute/path/to/phpmussel.php`

I've tested it and it works without any problems. This could be added to the readme.

**Comment by Maikuolan** [comment]
Good point.

I'll get started on that. :-)

**Comment by DanielRuf** [comment]
Can we close this issue?

**Comment by Maikuolan** [comment]
Doing now. '^.^
