### ISSUE TITLE
better description for $phpMussel['split_nibble']()

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#90]
The low and high nibble are only the parts of the first byte. Multibyte characters like `ü` have more than one byte, so `$phpMussel['split_nibble']()` returns the H and L nibble of the first byte which is correct but we should mention that is is the first byte only.

But if we want to return all nibbles, we should count the bytes and also return H and L nibble of the second (or third byte too) if this is needed. 

See:
https://books.google.de/books?id=LSfKMkrXRgUC&pg=PA115&lpg=PA115&dq=nibble+first+byte&source=bl&ots=Ukn8fklsRS&sig=uWgiGPPyt5u6ybXSzf0YUNF4oEE&hl=de&sa=X&ved=0ahUKEwjKwvau29LMAhVCXiwKHTXkCyAQ6AEIUzAG#v=onepage&q=nibble%20first%20byte&f=false

**Comment by Maikuolan** [comment]
Makes sense. :+1: 

I think it should be possible to slightly simplify this function, too; I'll upload a new commit for this now.

**Comment by Maikuolan** [comment]
Okay, done. :-)

Let me know what you reckon about the change.

**Comment by DanielRuf** [comment]
The description for the parameter `... the high nibble of the input string ...` does not contain the `first byte` information but the description of the function. Anyway, the commit is ok and is now better than before =)

**Comment by Maikuolan** [comment]
:+1:
