### ISSUE TITLE
better / faster $phpMussel['explode_bits']() implementation

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#91]
We should use `unpack` and `base_convert` to simplify this instead of using bit operations.

See http://stackoverflow.com/a/6382880

I did a small benchmark

``` php
$phpMussel['explode_bits'] = function ($n) {
    if (is_array($n)) {
        return '';
    }
    $c = strlen($n);
    for ($a = array(), $i = 0, $j = 0; $i < $c; $i++, $j += 8) {
        $a[$j] = (bool)(($n[$i] & "\x80") === "\x80");
        $a[$j+1] = (bool)(($n[$i] & "\x40") === "\x40");
        $a[$j+2] = (bool)(($n[$i] & "\x20") === "\x20");
        $a[$j+3] = (bool)(($n[$i] & "\x10") === "\x10");
        $a[$j+4] = (bool)(($n[$i] & "\x08") === "\x08");
        $a[$j+5] = (bool)(($n[$i] & "\x04") === "\x04");
        $a[$j+6] = (bool)(($n[$i] & "\x02") === "\x02");
        $a[$j+7] = (bool)(($n[$i] & "\x01") === "\x01");
    }
    return $a;
};

$phpMussel['explode_bits_new']= function($n){
    $value = unpack('H*', $n);
    //return base_convert($value[1], 16, 2);
    return str_pad(base_convert($value[1], 16, 2), 8, '0', STR_PAD_LEFT);
};

$start=microtime(true);
for($i=0;$i<1000000;$i++)$phpMussel['explode_bits']("ü");
echo microtime(true)-$start;
echo "\n";
$start=microtime(true);
for($i=0;$i<1000000;$i++)$phpMussel['explode_bits_new']("ü");
echo microtime(true)-$start;
```

``` php
if(!$phpMussel['explode_bits']("t")[0])echo "false";
if($phpMussel['explode_bits']("t")[1])echo "true";
if(!$phpMussel['explode_bits_new']("t")[0])echo "false";
if($phpMussel['explode_bits_new']("t")[1])echo "true";
```

This works because 1 is equal to true and 0 equal to false (==) but not identical. We could also typecast to bool in the correpsonding lines if needed.

See https://github.com/Maikuolan/phpMussel/blob/master/vault/functions.php#L7467-L7468

`$phpMussel['explode_bits']` took 1.9357340335846 seconds
`$phpMussel['explode_bits_new']` took 0.91002702713013 seconds

Tests were done under PHP 7. `$phpMussel['explode_bits_new']` needs less code, is ~50% faster and is better to read too.

For characters with just one byte, it is ~20-30% faster

`$phpMussel['explode_bits']` took 1.0951771736145 seconds
`$phpMussel['explode_bits_new']` took 0.84796118736267 seconds

The performance dramatically decreases when using `$phpMussel['explode_bits_new']` with a character / byte which has a a code point greater than 127 / more than 1 byte.

We should also optimise `$phpMussel['implode_bits']` in the same way and use `pack`

`pack('H*', base_convert('01....', 2, 16))`

**Comment by Maikuolan** [comment]
That definitely looks like a significant improvement performance there with the proposed change, and this is definitely always something welcomed. :+1: 

About to get some sleep for the night, but I'll a look a little more closely at this in the morning when I wake up.

**Comment by DanielRuf** [comment]
Sure, no problem. Just wanted to get your feedback on this and implement this together with you. The DocBlock comments also have to be changed and I am not sure if / why we need the boolean array. But this should be the least problem. Exploding the resulting binary value and converting each element to boolean for example with `array_map` should be sufficient and still faster than applying binary operations on each byte.

**Comment by DanielRuf** [comment]
Update: adding left padding to get also leading zeroes and always have exactly 8, 16, ... bits, currently we use just 8 bits but the implementation of the function should be scalable (like the solution I wrote) and independant of our implementation.

**Comment by Maikuolan** [comment]
I think there may be problems with using `base_convert()` for very large strings/numbers/etc. I was playing around with the new proposed function a little, and I encountered some unexpected behaviour with larger inputs: Sometimes, the actual results of the function weren't as would be expected (large strings of only `0`, for example).

Maybe we could hybridise the two; Use the faster/newer procedure for smaller strings/numbers/etc, and then the slower/older procedure (which seems to be able to handle larger strings better) for larger strings/numbers/etc (and normalised to have the same output regardless of procedure, of course)?

**Comment by Maikuolan** [comment]
``` PHP
<?php
/** Reversibility test for base_convert(). */

$phpMussel['test'] = function ($n) {
    $value = unpack('H*', $n);
    $new = base_convert($value[1], 16, 2);
    $old = base_convert($new, 2, 16);
    return ($old == $value[1]) ? true : false;
};

echo $phpMussel['test']('Foo') ? "Good\n" : "Bad\n";
echo $phpMussel['test']('FooBar') ? "Good\n" : "Bad\n";
echo $phpMussel['test']('FooBarF') ? "Good\n" : "Bad\n";
echo $phpMussel['test']('FooBarFo') ? "Good\n" : "Bad\n";
echo $phpMussel['test']('FooBarFoo') ? "Good\n" : "Bad\n";

/* Results:
 * ===
 * Good
 * Good
 * Bad
 * Bad
 * Bad
 */
```

**Comment by Maikuolan** [comment]
Generally, this problem with `base_convert()` shouldn't affect us currently, because the largest string currently being parsed by `$phpMussel['explode_bits']()` anywhere in phpMussel is only 2 bytes long anyway, but accounting for this problem could be good for future-proofing and to avoid problems for others that might adopt the code.

I'll write up a draft hybrid in a moment.

**Comment by Maikuolan** [comment]
How's this:

``` PHP
<?php
/** Hybrid draft for $phpMussel['explode_bits'](); */

$phpMussel['explode_bits'] = function ($n) {
    if (!$c = strlen($n)) {
        return '';
    }
    if ($c < 4) {
        $pad = $c * 8;
        $value = unpack('H*', $n);
        return str_pad(base_convert($value[1], 16, 2), $pad, '0', STR_PAD_LEFT);
    }
    for ($out = '', $i = 0; $i < $c; $i++) {
        $out .= (($n[$i] & "\x80") === "\x80") ? '1' : '0';
        $out .= (($n[$i] & "\x40") === "\x40") ? '1' : '0';
        $out .= (($n[$i] & "\x20") === "\x20") ? '1' : '0';
        $out .= (($n[$i] & "\x10") === "\x10") ? '1' : '0';
        $out .= (($n[$i] & "\x08") === "\x08") ? '1' : '0';
        $out .= (($n[$i] & "\x04") === "\x04") ? '1' : '0';
        $out .= (($n[$i] & "\x02") === "\x02") ? '1' : '0';
        $out .= (($n[$i] & "\x01") === "\x01") ? '1' : '0';
    }
    return $out;
};

echo $phpMussel['explode_bits']('F') . "\n";
echo $phpMussel['explode_bits']('Fo') . "\n";
echo $phpMussel['explode_bits']('Foo') . "\n";
echo $phpMussel['explode_bits']('FooB') . "\n";
echo $phpMussel['explode_bits']('FooBa') . "\n";
echo $phpMussel['explode_bits']('FooBar') . "\n";
echo $phpMussel['explode_bits']('FooBarF') . "\n";
echo $phpMussel['explode_bits']('FooBarFo') . "\n";
echo $phpMussel['explode_bits']('FooBarFoo') . "\n";

/** Results:
 * ===
 * 01000110
 * 0100011001101111
 * 010001100110111101101111
 * 01000110011011110110111101000010
 * 0100011001101111011011110100001001100001
 * 010001100110111101101111010000100110000101110010
 * 01000110011011110110111101000010011000010111001001000110
 * 0100011001101111011011110100001001100001011100100100011001101111
 * 010001100110111101101111010000100110000101110010010001100110111101101111
 */
```

It's a little tricky to gage exactly where the cut-off should be between the old and new procedure (because I'm not entirely sure exactly what the cause of the problem with `base_convert()` is, and I'm not sure if the problems are likely to appear at the same point for every system; it could be a 32-bit/64-bit thing, or could have similar implications), but the above draft assumes a cut-off of 4 bytes (x<4 for newer/faster and x=>4 for older/slower).

I've also modified the padding as so that it can be a multiple of 8 of the length of the string, rather than just exactly 8 (which could still result in 0's being cut for larger strings/numbers/etc).

**Comment by DanielRuf** [comment]
It is because of the big internal numbers which could hit the limits.

For large numbers, BCMath should be always used, see http://php.net/manual/de/function.base-convert.php#106546

Will benchmark this later today. Sould be still faster than the manual bit operations as BCMath is meant for big number calculations.

**Comment by DanielRuf** [comment]
Well, your old function converted each character to its binary presentation but this might be wrong. Also the vlaue is too big for most platforms, BCMath is required.

**Comment by DanielRuf** [comment]
This is normal because of the precision loss of `base_convert`. Will try to find a solution. See http://php.net/manual/en/function.base-convert.php

> Warning
> base_convert() may lose precision on large numbers due to properties related to the internal "double" or "float" type used. Please see the Floating point numbers section in the manual for more specific information and limitations.

**Comment by DanielRuf** [comment]
What about this?

``` php
$phpMussel['explode_bits_new'] = function ($n) { 
    $out = '';
    $len = strlen($n);
    for ($i = 0; $i < $len; $i++)
    $out .= str_pad(decbin(ord($n[$i])), 8, '0', STR_PAD_LEFT);
    return $out;
};

$phpMussel['explode_bits'] = function ($n) {
    if (!$c = strlen($n)) {
        return '';
    }
    if ($c < 4) {
        $pad = $c * 8;
        $value = unpack('H*', $n);
        return str_pad(base_convert($value[1], 16, 2), $pad, '0', STR_PAD_LEFT);
    }
    for ($out = '', $i = 0; $i < $c; $i++) {
        $out .= (($n[$i] & "\x80") === "\x80") ? '1' : '0';
        $out .= (($n[$i] & "\x40") === "\x40") ? '1' : '0';
        $out .= (($n[$i] & "\x20") === "\x20") ? '1' : '0';
        $out .= (($n[$i] & "\x10") === "\x10") ? '1' : '0';
        $out .= (($n[$i] & "\x08") === "\x08") ? '1' : '0';
        $out .= (($n[$i] & "\x04") === "\x04") ? '1' : '0';
        $out .= (($n[$i] & "\x02") === "\x02") ? '1' : '0';
        $out .= (($n[$i] & "\x01") === "\x01") ? '1' : '0';
    }
    return $out;
};


$start=microtime(true);
for($i=0;$i<1000000;$i++)$phpMussel['explode_bits']("FooBarFoo");
echo microtime(true)-$start;
echo "\n";
$start=microtime(true);
for($i=0;$i<1000000;$i++)$phpMussel['explode_bits_new']("FooBarFoo");
echo microtime(true)-$start;

/*
old: 9.4269449710846
new: 3.8462820053101
*/

$phpMussel['implode_bits_new'] = function($n){
    $chars_chunks = str_split($n, 8);
    $num = count($chars_chunks);
    $out = '';
    for($i = 0; $i < $num; $i++) $out .= chr(bindec($chars_chunks[$i]));
    return $out;
};
```

also faster than the first version:

``` php
$phpMussel['explode_bits_new'] = function ($n) { 
    $out = '';
    $len = strlen($n);
    for ($i = 0; $i < $len; $i++)
    $out .= str_pad(decbin(ord($n[$i])), 8, '0', STR_PAD_LEFT);
    return $out;
};

$phpMussel['explode_bits_new_old']= function($n){
    $value = unpack('H*', $n);
    //return base_convert($value[1], 16, 2);
    return str_pad(base_convert($value[1], 16, 2), 8, '0', STR_PAD_LEFT);
};

$phpMussel['explode_bits'] = function ($n) {
    if (!$c = strlen($n)) {
        return '';
    }
    if ($c < 4) {
        $pad = $c * 8;
        $value = unpack('H*', $n);
        return str_pad(base_convert($value[1], 16, 2), $pad, '0', STR_PAD_LEFT);
    }
    for ($out = '', $i = 0; $i < $c; $i++) {
        $out .= (($n[$i] & "\x80") === "\x80") ? '1' : '0';
        $out .= (($n[$i] & "\x40") === "\x40") ? '1' : '0';
        $out .= (($n[$i] & "\x20") === "\x20") ? '1' : '0';
        $out .= (($n[$i] & "\x10") === "\x10") ? '1' : '0';
        $out .= (($n[$i] & "\x08") === "\x08") ? '1' : '0';
        $out .= (($n[$i] & "\x04") === "\x04") ? '1' : '0';
        $out .= (($n[$i] & "\x02") === "\x02") ? '1' : '0';
        $out .= (($n[$i] & "\x01") === "\x01") ? '1' : '0';
    }
    return $out;
};


$start=microtime(true);
for($i=0;$i<1000000;$i++)$phpMussel['explode_bits']("FooBar");
echo microtime(true)-$start;
echo "\n";
$start=microtime(true);
for($i=0;$i<1000000;$i++)$phpMussel['explode_bits_new_old']("FooBar");
echo microtime(true)-$start;
echo "\n";
$start=microtime(true);
for($i=0;$i<1000000;$i++)$phpMussel['explode_bits_new']("FooBar");
echo microtime(true)-$start;

/*
old: 6.0306529998779
new_old: 2.9187521934509
new: 2.5350930690765
*/
```

**Comment by Maikuolan** [comment]
Very nice; I think we've got it. :+1: 

Testing the latest revision (copy/paste from your latest reply):
```PHP
$a = function ($n) {
    $out = '';
    $len = strlen($n);
    for ($i = 0; $i < $len; $i++) {
        $out .= str_pad(decbin(ord($n[$i])), 8, '0', STR_PAD_LEFT);
    }
    return $out;
};
```

..Against the hybrid proposal I'd posted earlier, I haven't found any problems at all, and the performance improvements on my end were rather drastic.

Against 100,000 calls to each version of the closure with variable length strings, I had these averages:
```
Latest revision: 1.3650019168854
Hybrid proposal: 3.56610596179965
```
(Or averaged against each other, that makes the latest revision about ~2.6 times faster).

I think we should use it.

In addition.. The new closure for imploding bits is definitely better than the old version:
```PHP
<?php
/** Comparison between the two $phpMussel['implode_bits'](); closures. */

$a = function($n) {
    $chars_chunks = str_split($n, 8);
    $num = count($chars_chunks);
    $out = '';
    for ($i = 0; $i < $num; $i++) {
        $out .= chr(bindec($chars_chunks[$i]));
    }
    return $out;
};

$b = function ($n) {
    $c = count($n);
    for ($x = '', $i = 0; $i < $c; $i += 8) {
        $a = "\xff";
        if ($n[$i]) {
            $a = $a ^ "\x80";
        }
        if ($n[$i + 1]) {
            $a = $a ^ "\x40";
        }
        if ($n[$i + 2]) {
            $a = $a ^ "\x20";
        }
        if ($n[$i + 3]) {
            $a = $a ^ "\x10";
        }
        if ($n[$i + 4]) {
            $a = $a ^ "\x08";
        }
        if ($n[$i + 5]) {
            $a = $a ^ "\x04";
        }
        if ($n[$i + 6]) {
            $a = $a ^ "\x02";
        }
        if ($n[$i + 7]) {
            $a = $a ^ "\x01";
        }
        $x .= ~$a;
    }
    return $x;
};

echo "\n\n";
$m = microtime();
$t = substr($m, 0, strpos($m, ' ')) + substr($m, strpos($m, ' '));
for($i = 0; $i < 100000; $i++) {
    $x = $a('010001100110111101101111010000100110000101110010010001100110111101101111');
}
echo $x . "\n\n";
$m = microtime();
$t = (substr($m, 0, strpos($m, ' ')) + substr($m, strpos($m, ' '))) - $t;
echo $t . "\n\n";
$m = microtime();
$t = substr($m, 0, strpos($m, ' ')) + substr($m, strpos($m, ' '));
for($i = 0; $i < 100000; $i++) {
    $x = $b('010001100110111101101111010000100110000101110010010001100110111101101111');
}
echo $x . "\n\n";
$m = microtime();
$t = (substr($m, 0, strpos($m, ' ')) + substr($m, strpos($m, ' '))) - $t;
echo $t . "\n\n";

/**
 * Results:
 * ===
 * FooBarFoo
 * 
 * 0.25000095367432
 * 
 * F
 * 
 * 0.089999914169312
 */
```

..For two reasons:

1. The old version isn't entirely reversible anyway for larger strings (because it only returns the first reconstructed byte anyway, instead of the entire string), which is a problem in itself.

2. The new version works out to be about ~2.78 times faster than the old version.

I'll add this to the codebase now. :+1:

**Comment by Maikuolan** [comment]
Very nice; I think we've got it. :+1: 

Testing the latest revision (copy/paste from your latest reply):

``` PHP
$a = function ($n) {
    $out = '';
    $len = strlen($n);
    for ($i = 0; $i < $len; $i++) {
        $out .= str_pad(decbin(ord($n[$i])), 8, '0', STR_PAD_LEFT);
    }
    return $out;
};
```

..Against the hybrid proposal I'd posted earlier, I haven't found any problems at all, and the performance improvements on my end were rather drastic.

Against 100,000 calls to each version of the closure with variable length strings, I had these averages:

```
Latest revision: 1.3650019168854
Hybrid proposal: 3.56610596179965
```

(Or averaged against each other, that makes the latest revision about ~2.6 times faster).

I think we should use it.

In addition.. The new closure for imploding bits is definitely better than the old version:

``` PHP
<?php
/** Comparison between the two $phpMussel['implode_bits'](); closures. */

$a = function($n) {
    $chars_chunks = str_split($n, 8);
    $num = count($chars_chunks);
    $out = '';
    for ($i = 0; $i < $num; $i++) {
        $out .= chr(bindec($chars_chunks[$i]));
    }
    return $out;
};

$b = function ($n) {
    $c = strlen($n);
    for ($x = '', $i = 0; $i < $c; $i += 8) {
        $a = "\xff";
        if ($n[$i]) {
            $a = $a ^ "\x80";
        }
        if ($n[$i + 1]) {
            $a = $a ^ "\x40";
        }
        if ($n[$i + 2]) {
            $a = $a ^ "\x20";
        }
        if ($n[$i + 3]) {
            $a = $a ^ "\x10";
        }
        if ($n[$i + 4]) {
            $a = $a ^ "\x08";
        }
        if ($n[$i + 5]) {
            $a = $a ^ "\x04";
        }
        if ($n[$i + 6]) {
            $a = $a ^ "\x02";
        }
        if ($n[$i + 7]) {
            $a = $a ^ "\x01";
        }
        $x .= ~$a;
    }
    return $x;
};

echo "\n\n";
$m = microtime();
$t = substr($m, 0, strpos($m, ' ')) + substr($m, strpos($m, ' '));
for($i = 0; $i < 100000; $i++) {
    $x = $a('010001100110111101101111010000100110000101110010010001100110111101101111');
}
echo $x . "\n\n";
$m = microtime();
$t = (substr($m, 0, strpos($m, ' ')) + substr($m, strpos($m, ' '))) - $t;
echo $t . "\n\n";
$m = microtime();
$t = substr($m, 0, strpos($m, ' ')) + substr($m, strpos($m, ' '));
for($i = 0; $i < 100000; $i++) {
    $x = $b('010001100110111101101111010000100110000101110010010001100110111101101111');
}
echo $x . "\n\n";
$m = microtime();
$t = (substr($m, 0, strpos($m, ' ')) + substr($m, strpos($m, ' '))) - $t;
echo $t . "\n\n";

/**
 * Results:
 * ===
 * FooBarFoo
 * 
 * 0.25999999046326
 * 
 * FooBarFoo
 * 
 * 0.67000102996826
 */
```

The new version works out to be about ~2.58 times faster than the old version, which is a good improvement.

I'll add these to the codebase now. :+1:
