### ISSUE TITLE
install on Ubuntu 14.04

### ISSUE THREAD

**Issue by msouzarunner** [phpMussel/phpMussel#95]
Hello, Maikuolan

    I installed the phpMussel on a machine with Ubuntu 14.04 with PHP 5.5.9 and PCRE Library Version 8.31 2012-07-06, given the appropriate privileges folders.

    I made the code below and is giving an error for me strange, I need help.

<?php

include 'phpmussel.php';

$file = '/tmp/testvirus.txt' ;
$results = `$phpMussel["Scan"]($file,` true, true);
echo $results;

?>

   Mistakes are these:

Notice: Undefined variable: phpMussel in /var/www/html/teste/phpMussel-master/scan.php on line 6

Fatal error: Function name must be a string in /var/www/html/teste/phpMussel-master/scan.php on line 6

**Comment by Maikuolan** [comment]
Hello msouzarunner,

Thank you for reporting this. :-)

Have you disabled the `cleanup` directive in `phpmussel.ini`?

``` INI
; Unset variables and cache used by the script after the initial upload
; scanning? False = No; True = Yes [Default]. If you -aren't- using the script
; beyond the initial scanning of uploads, you should set this to "true" (yes),
; to minimize memory usage. If you -are- using the script beyond the initial
; scanning of uploads, should set to "false" (no), to avoid unnecessarily
; reloading duplicate data into memory. In general practice, it should usually
; be set to "true", but, if you do this, you won't be able to use the script
; for anything other than the initial file upload scanning.
cleanup=true
```

What this means is that, when `cleanup=true`, phpMussel will attempt to unset itself from memory immediately after it finishes loading and processing its most basic instructions. To use the scan functionality after this time, we need to set this to `false` (when `cleanup=false`, it won't do this, and it can be manually unset later, or whenever PHP terminates, alongside everything else).

**Comment by msouzarunner** [comment]
Hello, Maikuolan

Perfect, worked, Grateful for the help.

  I'm starting to use the phpMussel. I have a separate script to use Clamav and another to trigger VirusTotal, with this his work unifies the two operations with much more appeal.

Congratulations for your work

**Comment by Maikuolan** [comment]
No problem; Happy to help. :-)
