### ISSUE TITLE
Queuing

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#97]
There are a number of possible features that aren't really feasible to be added to phpMussel as it is currently, but which could feasibly be added in the future if phpMussel supported message/task queuing (_for example; if a new malicious sample is discovered via heuristics, to be able to silently send it to various anti-virus vendors in the background, without breaking the user experience; or, if a VirusTotal API key exists in the configuration, and with some appropriate future but currently non-existent directive being enabled, when a file is scanned which isn't flagged as being malicious by phpMussel and which isn't recognised by the VirusTotal API, if the file matches certain of-interest criteria - whether it be self-executable, a self-contained archive, a multi-layered OLE object, etc - to be able to silently send it to VirusTotal to be scanned, also, without breaking the user experience_).

These features, I think, could provide for some cool and interesting additions to phpMussel, but the problem with message/task queuing, is that it tends to not be something universally accepted across all hosting providers - especially shared hosting providers, which tend to not allow queuing by default, and tend to restrict away from their users the access necessary for enabling queuing and other similar systems (and generally, any applications that actually require proper queuing systems tend to be better suited for dedicated hosts, anyhow).

It would be possible to roll something rudimentary of our own, if we wanted to - In the absence of a universally accepted database schema or system for dealing with queues, writing to and reading from simple serialised flatfiles would probably be sufficient for shared hosting environments, and could be handled using some external PHP file for processing queues, called via cron, etc; It should work well enough generally, but may seem a little adhoc and haphazard, and perhaps isn't ideal.

That aside, assuming we had some generally well-accepted queuing system to work with, and we built some features to rely upon it - There remains the question of how many users would be likely to actually bother using it (I'm assuming that setting up something like this, although not particularly difficult to do, would nonetheless be slightly more difficult than the standard installation and configuration process for phpMussel, that it would serve yet another additional step to getting everything working, and many users would probably just consider it to not have enough value to bother enabling it anyhow).

If it's something that could be beneficial to some users, but which most users wouldn't bother using, we could build it as an external plugin rather than as a core feature (this wouldn't be much more difficult to do really anyhow), but whether we _should_ do something like this, I'm not sure; Whether we should try to build something like this, or whether we should stay away from it entirely.

Anyhow, curious about your thoughts, and whether this is an issue worth exploring.

**Comment by DanielRuf** [comment]
Definitely a good idea so we have some sort of community based database and we give something back to the vendors.

So far I just know the mailinglist from http://www.techsupportalert.com/content/how-report-malware-or-false-positives-multiple-antivirus-vendors.htm#Easily_Submit_Malware_To_All_Vendors and VirusTotal (and alternatives) which send the samples to the AV vendors.

**Comment by Maikuolan** [comment]
Adding "Help Wanted" label.

**Comment by Maikuolan** [comment]
Closing because stale + implies a higher level of complexity than most users would be comfortable with, I think.
