### ISSUE TITLE
Wrong language key?

### ISSUE THREAD

**Issue by mtrefzer** [phpMussel/phpMussel#98]
Hello Maikuolan,
I'm not sure, but as far as see, the key 'upload_error_34' in the language files ist never used.
In upload.php the keys 'upload_error_3' and 'upload_error_4' are used instead and they don't exist in the language files.

**Comment by Maikuolan** [comment]
Whoops.. Good catch! I'll sort that out now. :+1:

**Comment by Maikuolan** [comment]
Fixed (https://github.com/Maikuolan/phpMussel/commit/e57323305658c110e7aef83b6d28a590d194dcfc).
