### ISSUE TITLE
plugin hook 'before_html_out' never executed

### ISSUE THREAD

**Issue by mtrefzer** [phpMussel/phpMussel#99]
Hello Maikuolan,
I tried out your 'Maikuolan/plugin-boilerplate-v1' with the actual sources and found that in vault/upload.php line 600 always runs into line 606 and the plugincode is never executed.
Shouldn't you fetch $HookID for the key 'before_html_out' instead of 'during_scan'?

If I'm correct, you also should check the other plugin hooks:
vault/functions.php line 6261, 6732, 7724
vault/controls.php line 76, 181

I also checked your pugin 'Maikuolan/plugin-notifications' here you are using $phpMussel['MusselConfig'] this should be $phpMussel['Config'] instead, because the key MusselConfig does't exist.

**Comment by Maikuolan** [comment]
Cheers. :+1: 

You are correct, and good spotting.

Fixing these now. :-)

**Comment by Maikuolan** [comment]
Fixed. :-)
